#+MACRO: ts (eval(mwp-get-ts+7  'org-mwp-classtimes-calibrate 2))
#+STARTUP: customtime
#+SETUPFILE: ./setup.org
#+ORG_LMS_SECTION: announcement

* Welcome! And Website...
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 694692
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/157875/discussion_topics/694692
:ORG_LMS_POSTED_AT: 2020-07-07T06:55:15Z
:END:

Welcome, everyone, to WDW235! I'm looking forward to meeting you all very soon. [[https://q.utoronto.ca/courses/157875][The Quercus webstie is now live]], and we will be meeting synchronously at 2pm [[https://q.utoronto.ca/courses/157875/external_tools/246][Using BB Collaborate]]. If you haven't used it before... it's not quite as good as Zoom! But it's what we've got for now.  Please turn your video *off* when you connect to the classroom, as otherwise bandwidth will be a real problem.  Since I won't be able to see your faces, I'd really appreciate it if you could *add a profile picture* so that I can tell you're ahuman being. The instructions for doing so [[https://help.blackboard.com/Collaborate/Ultra/Participant/Get_Started#add-a-profile-picture_OTP-2][are here]].

I'll also be asking you to [[https://join.slack.com/t/uoftdh/shared_invite/zt-fq2pcjk4-Y3Vvyu6~tNDjYbfH~T6mJA][join Slack]] and engage in conversation there.  This is my first time teaching a sizeable lecture class in this format, so there will be a bit of learning for all of us.  I do think Slack will help us with that.  [[https://slack.com/intl/en-ca/downloads][Be sure to download the desktop app]], which is somewhat easier to usee than the browser-based version.  

I'm very much looking forward to this class, which I'll be teaching for the third time. I normally use lower-level tools than we'll be using in this course (that is, I tend to program in a text-based environment, rather than using these graphic user interfaces), so I'm looking forward to exploring some of these amazing DH projects with you. 

There will be *many* more details forthcoming, both in class and on the website.  

See you in class in a few hours!
 
* Please sign up for Slack!
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 695104
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/157875/discussion_topics/695104
:ORG_LMS_POSTED_AT: 2020-07-07T16:43:35Z
:END:

We'll be using it in class today.  [[https://join.slack.com/t/uoftdh/shared_invite/zt-fq2pcjk4-Y3Vvyu6~tNDjYbfH~T6mJA][Here is the link again]]. About 10 of you have signed up so far but the more who have done it before class, the better.  Thanks! 

* Technical difficulties!
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 697298
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/157875/discussion_topics/697298
:ORG_LMS_POSTED_AT: 2020-07-09T15:27:17Z
:END:

I'm having some technical difficulties with video recordings so unfortunately you will have to sit through lecture live today. My apologies!

* Omeka @ U of T

We're going to be practicing with the Omeka framework today.  It is a little bit difficult to navigate so it might be useful for you to at least login before class and take a look around. You will be *sharing* a login with others, which I'm afraid can be a bit frustrating, but as I don't have admin access to the site this is the best I can do for now (I may make some changes later if I'm able to). Login data is also a bit out of date but you should be able to figure it out :-) 

- login here: https://spatial-humanities.library.utoronto.ca/admin/users/login
- Username: WDW235-2019-evening
- Password: 2019-evening

Thanks!  

* Data visualization today -- Downlad Tableau Public!
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 718435
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/157875/discussion_topics/718435
:ORG_LMS_POSTED_AT: 2020-07-30T15:25:51Z
:END:

We are entering a part of the class in which we will really be missing the special classroom we normally have! For today's class, we'll be using the public version of the Tableau Desktop software.  We'll walk through some basic visualization examples, but it will definitely be slower than it normally would and you will have to work more independently than otherwise would be the case.

Next class we will take these skills and apply them to some slightly more interesting data

To prepare for this afternoons's class,

- [[https://public.tableau.com/en-us/s/][Download the Tableau Public software]] You'll need a mac of windows computer, or a windows virtual machine on linux (I had a bit of trouble with my license key so I will be coming to you live from windows land)
- [[https://maps.library.utoronto.ca/workshops/IntroDataViz/index.php][Download the workshop example data files]] and unzip them. Be sure you know how to find them again (probably in you ~Downloads~ folder)
- [[https://public.tableau.com/][Create an account at Tableau by clicking on the "Sign Up" Button here]]

Though proprietary and a bit evil, Tableau is an immensely powerful tool and totally worth getting to know.  You may find it comes in handy in other contexts. 

* Data Cleaning Today -- Sorry Please Download these files!
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 725397
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/157875/discussion_topics/725397
:ORG_LMS_POSTED_AT: 2020-08-06T17:40:52Z
:END:
Oops, forgot to tell you about some stuff you need to download for today's class!
- [[https://openrefine.org/download.html][Please download and install the OpenRefine Software!]] It should be compatible with everyone's laptops, unlike Tableau!
- [[https://maps.library.utoronto.ca/workshops/OpenRefine/][Please go to the Maps & Data Library website and download "WorkshopFiles.zip" fro mthis address]]

  Also, there may be an issue with video in today's class... which will be somewhat difficult if it turns out to be ture! If so, we'll muddle through as best we can. 

* Slides for Lecture 2
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 697686
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/157875/discussion_topics/697686
:ORG_LMS_POSTED_AT: 2020-07-09T18:06:44Z
:END:

They're [[https://q.utoronto.ca/courses/157875/files/folder/Lectures?preview=7954856][on Quercus (just remembered to upload now)]]

* Assignment 1
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 374399
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/374399
:ORG_LMS_POSTED_AT: 2019-09-12T14:18:57Z
:END:
Just a quick note that [[https://q.utoronto.ca/courses/127426/assignments/221044][the first assignment is now online]].  Please take a look before class today, and esp. look for any errors or confusion so I can correct them! 

* Today's Lecture Notes
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 695268
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/157875/discussion_topics/695268
:ORG_LMS_POSTED_AT: 2020-07-07T17:55:50Z
:END:
Had some trouble getting lecture notes online in their natural environment but [[https://q.utoronto.ca/courses/157875/files/folder/Lectures][you can find a PDF here in Quercus for now]]. You will likely want to follow along -- we will probably skip some stuff today in favour of an async presentation in the next 36 hours. 

* Argh! Once again, lecture will be live today. Code editors!
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 702103
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/157875/discussion_topics/702103
:ORG_LMS_POSTED_AT: 2020-07-14T15:25:37Z
:END:
Sorry for the repeated technical issues (irony is fully appreciated). We'll have to do class live today.  Before class starts, *please* take time to install a text editor and open it up/explore. As I mention elsewhere, [[https://code.visualstudio.com/download][I strongly recommend Visual Studio Code]] and a [[https://marketplace.visualstudio.com/search?term=live%20preview&target=VSCode&category=All%20categories&sortBy=Relevance][Live Preview Extension]] (if you like, you can also install the [[https://marketplace.visualstudio.com/items?itemName=digital-history.history-hack-pack][History Hack Pack]], which I maintain for use in HIS393; but it has a lot of stuff you won't need for this assignment or for this class).

Getting VS Code installed is probably the best use you can make of your time.  You might also want to [[https://github.com/DigitalHistory/poem-json-project/releases/][download and unzip the files for Assignment 2]]. 

* In-Class Exercise
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 702137
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/157875/discussion_topics/702137
:ORG_LMS_POSTED_AT: 2020-07-14T15:58:13Z
:END:
Today we'll be walking through the assignment with *a different poem* as an example. Please download [[https://q.utoronto.ca/courses/157875/files/folder/Handouts][al-kolera.zip from the "Handouts" folder in the Quercus files]]. Thanks!

* Lectures online!
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 705435
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/157875/discussion_topics/705435
:ORG_LMS_POSTED_AT: 2020-07-16T16:58:52Z
:END:
Shoot! I forgot to announce this except in slack -- lectures are online here:
https://www.youtube.com/playlist?list=PLLY-W2GKX2ZKWlJa7auAkC__nAP2GVrQU


Why don't we start class a little late, say 2:30, so you have time to watch these first.

* Readings for Tomorrow!
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 709653
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/157875/discussion_topics/709653
:ORG_LMS_POSTED_AT: 2020-07-21T11:16:17Z
:END:
Hello class,

I have just realized that the syllabus is missing the readings for tomorrow. My apologies!

Please read Edgar Allen Poe's short story [[https://www.gutenberg.org/files/1064/1064-h/1064-h.htm][The Masque of the Red Death]] and also please make at least an attempt at the more difficult [[https://q.utoronto.ca/courses/157875/files/folder/Readings][The Meaning of Contagion]] by Margaret Pelling (link is to a folder in Quercus).  Lectures to follow around noon though I'll also make some more specific announcements about the plan for the day.

See you soon!


* Lecture Notes; Assignment; Readings for Wednesday
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 301087
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/301087
:ORG_LMS_POSTED_AT: 2019-05-07T13:46:52Z
:END:
** Lecture Notes Fixed
 [[https://digitalhistory.github.io/wdw235/slides/01-intro][Slides from yesterday's lecture]] should now display more-or-less as expected; had some trouble w/ local images which has now been debugged :-) 

** Reflection Assignment 1
The Reflection assignment, which we will discuss more on Wednesday, is now up on both Quercus and [[https://digitalhistory.github.io/wdw235/assignment/][the course website]]. 

** Readings
We will *definitely* be taking time to discuss tomorrow's readings in class, so please make sure you actually read them.
- Miriam Posner's [[http://miriamposner.com/blog/how-did-they-make-that/][blog post]] discusses a number of projects -- please be sure to follow the (many) links whenever you can (some of them have aged a bit and are broken). Think about where your own interests lie.
- Ruecker & Galey's piece interweaves a numbrer of themes.  You yourself may not be especially interested in "how DH project should count when someone comes up for tenure", which is clearly one motivation of the essay, but the other themes will be relevant to many of you. You may find it a bit complex or convoluted, but please persevere.  You may find the going easier if you think about the following:
  - The discussion of design (pp. 405-07 and throughout) in many ways hinges on Winner's arguments in "Do Artifacts Have Politics", discussed on p. 406 and 407. Do you best to understand the main points. 
  - How should we understand the criteria for compelling arguments, which they summarize as "contestability, defensibility, and substantivity" (p.412ff)?
  - What do the authors mean when they suggest that digital objects can "reify an argument" (p.414)?
  - the [[http://www.textarc.org/PrintEditions.html][original TextArc]] is no longer live but [[http://vallandingham.me/textarc/][this cool partial replica]] can still be found ([[https://github.com/vlandham/textarc][code here]]) 

* Today's Class (<2019-09-19 Thu>)
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 384861
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/384861
:ORG_LMS_POSTED_AT: 2019-09-19T22:11:42Z
:END:

Today's class will be *much* less lecture-y, instead comprising a mix of discussion and workshopping.  Here's the approximate outline:

- discussion of today's readings, with an emphasis on [[http://muse.jhu.edu.myaccess.library.utoronto.ca/article/24448][deformance]]. Please spend some time thinking about the readings and any questions you might want to ask.  Consider the following:
  - why do the authors decide to use this new (made-up) word "deformance"?
  - what does this all have to do with technology (that is, why are we discussing here)? 
- workshopping with xml/xslt and TEI.  You will want to [[https://q.utoronto.ca/files/3647726/download?download_frd=1][read the handout]] and [[https://q.utoronto.ca/courses/99251/assignments/171001][the assignment]]
  - You'll need to [[http://fiddle.frameless.io/][navigate to the online xslt editor]] and paste in the code from the assignment.  

I think this will be fun today!   

* XML/TEI intro page!
I've published a page o n the website with some information about XML and TEI:

https://q.utoronto.ca/courses/127426/pages/introduction-to-xml-xslt-tei-and-html-long

Much of this is recapitulated in the handout, but we'll likely use this page a template for our lecture today, so you might want toread it. 

* Tonight: more deformance, more XML
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 393585
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/393585
:ORG_LMS_POSTED_AT: 2019-09-26T17:56:32Z
:END:

Hello everyone,

I wanted to let you know that tonight's class will be, in some ways, a rehash of last week at a higher level.  So 

- Make sure you've read the deformance piece this time! We'll discuss again. 
- I've put together a somewhat more realistic example of TEI and, incidentally, deformance.  You can [[https://titaniumbones.github.io/xslt-example/rj/rom-act2.xml][see it in action online here]], and you can [[https://github.com/titaniumbones/xslt-example/tree/master/rj][browse the actual code here]]. We will be  examining it in more detail tonight, and you may understand it a lot better if you look at it first. You can easily check it out by pasting the code into [[http://fiddle.frameless.io/][the XML fiddle site]], maybe using he "raw" view of [[https://raw.githubusercontent.com/titaniumbones/xslt-example/master/rj/rom-trans.xsl][the xsl stylesheet]] and [[https://raw.githubusercontent.com/titaniumbones/xslt-example/master/rj/rom-act2.xml][the full xml text]] to copy it more easily.  

* That last announcement
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 305537
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/305537
:ORG_LMS_POSTED_AT: 2019-05-16T15:45:23Z
:END:

it wasn't really an announcement, but a more detailed introduction to XML, XSLT, and HTML than we got in class. I'll distribute a bit more info soon -- maybe at the end of the day -- but I wanted to get this off ASAP so you could make use of it for you assignment!

* link to code
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 305014
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/305014
:ORG_LMS_POSTED_AT: 2019-05-15T16:09:25Z
:END:
[[https://hackmd.io/s/Bk0KFnYnE][here's the code for today]]

* Readings! Videos! Assignments! Discussions! Visits! Sign-ups!
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 400809
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/400809
:ORG_LMS_POSTED_AT: 2019-10-03T13:17:45Z
:END:
Hello Everyone,

This is a friendly reminder to you all to *do your work before class*. Tomorrow we'll be discussing these texts and videos: 
- William Noel, “[[http://www.ted.com/talks/william_noel_revealing_the_lost_codex_of_archimedes][Revealing the Lost Codex of Archimedes]]” (2012). [TED TALK]
- Bethany Nowviskie, “[[http://nowviskie.org/2014/anthropocene/][Digital Humanities in the Anthropocene]]”
- Eira Tansey, “[[http://eiratansey.com/2017/05/16/fierce-urgencies-2017/][When the Unbearable Becomes Inevitable: Archives and Climate Change]]” (2017).

*don't "forget" to read them!*

In addition, some announcements: 
- Really sorry about your assignments still not being marked.  Working on it! Some administrative confusion on my end.
- Some of you have been asking me about citation styles. I don't have strong preferences but I *do* strongly encourage you to use citation-management software, which will make your life *so much easier*. [[https://youtu.be/-hUxgC4EX2s][I recorded this short video introductio nto Zotero]] which I encourage you to watch.  
- You have hopefully started work on your second assignment. Good! If you're running into trouble, [[https://q.utoronto.ca/courses/127426/discussion_topics/400319][please use the discussion forum that I've set up for the assignment]]. And if you're feeling confident, perhaps head over to the discussion anyway to help your classmates out.
- Next week we'll be visiting the Fisher Rare Books Library. It will be really fun! The room we're using can only accomodate 20 students at a time, and the library closes at 8, so we will do this trip in *two separate groups* and potentially *end class an hour early* and bundle you off home for the holiday weekend (though I'll be around after 8 to answer questions). I've made a sign-up sheet which [[https://q.utoronto.ca/calendar?include_contexts=course_127426#view_name=week&view_start=2019-10-06][you can find in the course calendar on Quercus]]. Please use it! This is my first time making such a sign-up sheet, so I hope it works :-)

Enjoy the readings and see you in class!


* Omeka Login Instructions
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 400788
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/400788
:ORG_LMS_POSTED_AT: 2019-10-03T12:51:19Z
:END:
In this class we have a *shared login* to the local Omeka installation.  We'll talk more about protocols in class today. In this announcement, which should only be visible to the class, I'm giving you the login info: 

- Username: ~WDW235-2019-evening~
- Password: ~2019-evening~

Please feel free to login and look around before class, but *UNDER NO CIRCUNSTANCES MODIFY ANY RESOURCES THAT YOU FIND THERE.* Again, we'll learn how to use Omeka starting in class today. 

* Class *At Fisher Library* tonight
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: nil
:ORG_LMS_ANNOUNCEMENT_URL: nil
:ORG_LMS_POSTED_AT: nil
:END:

A reminder that we will be meeting in the Fisher Library tonight at 6:00 or at 7:00.  Some details:

- library is just south of Robarts, and is physically attached to it; [[https://www.google.com/maps?ll=43.664082,-79.398985&z=14&t=m&hl=en&gl=US&mapclient=embed&q=Thomas+Fisher+Rare+Book+Library+120+St+George+St+Toronto,+ON+M5S+1A5+Canada][here's a map]]
- Please *arrive early* as you will need to check your bags into the library lockers before heading down.  The 7:00 group will need to finish up at about 7:50 and will *start promptly at 7:00*, not at 7:10 -- please *do not come late*
- If you haven't signed up yet, then *you are in the 7:00 group* --the 6:00 group is full
- bring a notebook to jot down your thoughts, and a phone to take pictures if you wish.
- please come with thoughts and questions -- these are special texts and it's a real privilege to see them. Show your appreciation to the library by engaging thoughtfully and actively.

See you there, either at 6 or at 7!

* Consultation Sign-ups!
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 418506
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/418506
:ORG_LMS_POSTED_AT: 2019-10-22T12:16:13Z
:END:
Not sure whether I announced formally that consultation signups have been live since Friday.  Follow [[http://tuftsedtech.screenstepslive.com/s/18992/m/73355/l/810722-student-how-do-i-sign-up-for-an-appointment-group][these instructionsss]] to be sure that you have the course calendar activated in Quercus, and then please sign up -- only a few ooof you have done so so far, and the due date is coming up. 

* Tonight's Class; assignments (<2019-10-24 Thu>)
Remember that we Have a visit tonight form *Prof. Alexandra Bolintineanu*, who teaches the day class. She will be with us for about 30-45 minutes at the beginning of class. It will be important for you to have *browsed extensively* in the  [[https://samizdatcollections.library.utoronto.ca/][Project for the Study of Dissidence and Samizdat]]. You should know what "Samizdat" means and hopefully have some *questions* for Prof. B. about her presentation. Afterwards we will talk a bit more about Omeka and we'll take the last hour as time to make progress on your presentations.

I have finally handed back assignment 1, as I believe all of you are aware. I had hoped to be a bit further with Assignment 2 than I am; it will certainly be several days before I can get it back to you. I've read about a quarter of your papers so far and I'm pretty pleased with what you've done! 

If you skipped your appointment with me today... Don't do that again! 

See you this afternoon.

* Class *in Robarts* tonight
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 440683
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/440683
:ORG_LMS_POSTED_AT: 2019-11-14T02:24:27Z
:END:
Hello everyone! Welcome back! 

This week we have the first of two sequential -- and exciting -- workshops with Maps and Data Librarian [[https://onesearch.library.utoronto.ca/library-staff/26187/kelly-schultz][Kelly Schulz]].  This week's workshop is on data cleaning; you can see [[http://maps.library.utoronto.ca/workshops/OpenRefine/][the materials online here]], though our workshop won't follow this outline precisely.

Please arrive at Robarts Library *promptly* at 6:00PM. We'll be using the classroom on the 4th floor of Robarts, and the easiest way to get there wil lbe to take the escalator to the 4th floor; at the top of the escalator you'll see a whiteboard with an arrow pointing the way in. 

I'll look forward to seeing you all there -- please don't neglect to come!
* I forgot to send this out!
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 448308
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/448308
:ORG_LMS_POSTED_AT: 2019-11-21T21:38:03Z
:END:
Remember! We're meeting in Robarts again tonight! See you there!!
* Short Assignment 3 finally up!!
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 448404
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/448404
:ORG_LMS_POSTED_AT: 2019-11-21T23:23:09Z
:END:

Due a week from today.  link: 

https://q.utoronto.ca/courses/123949/assignments/250828
* Final Class!
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 453935
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/453935
:ORG_LMS_POSTED_AT: 2019-11-28T01:21:02Z
:END:
See you all tomorrow night for the last class of the year. I have fulfilled my promise to bake, but I'm counting on all of you as well!

Please take a quick look at your marks. If you see something that seems wrong -- e.g., if you have a 0 on an assignment but are sure that you handed it in -- please get in touch right away. I believe everything that has been handed in has now been marked.  

A few more remarks to follow soon. 
* Final Assignment Clarification
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 457885
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/457885
:ORG_LMS_POSTED_AT: 2019-12-02T19:15:50Z
:END:

Several of you have asked about the word count for the final assignment. My apologies for not clarifying this sooner.  As you'll recall, the assignment asks you to write at least 4 exhibit sections, ~introduction~, ~book~, ~context~, and ~insights~, and to include a ~works cited~ section. 

Each of those written sections (so, not ~works cited~) should be a minimum of 250-300 words, but *at least 1* of those sections should be substantially longer & represent sustained engagement with the text and the issues it raises (probably this will be ~context~ or ~insights~, or both, or an extra sectio nthat you add at your own discretion). I'm not able to give an exact word count because the main grading criteria will revolve not around length, but instead around *real engagement with an issue that matters.* So as you work, you should be focused as much as possible on that fundamental question -- "Have I explored an issue that I care about to an extent that I find satisfying?".

I hope this helps somewhat!
* Exhibits back online
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 458632
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/458632
:ORG_LMS_POSTED_AT: 2019-12-03T08:49:18Z
:END:

Several of you noticed that the exhibits suddenly disappeared from omeka yesterday afternoon. They appear to have been restored after an unexpected upgrade was triggered.  I believe everything is back to normal now. 
* Office Hours Today
As I've told several of you, I'm planning to be in my office today from 12-2.  
* Tomorrow's class -- PLEASE READ (also: Ref 1 assignment)
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 307088
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/307088
:ORG_LMS_POSTED_AT: 2019-05-22T00:03:58Z
:END:
I hope you all enjoyed your holiday weekend!

Tomorrow's class is *special* -- instead of meeting in our usual place we have the [[https://digitalhistory.github.io/wdw235/syllabus/syllabus/#6--data-openrefine][OpenRefine workshop]] in the [[https://mdl.library.utoronto.ca/][Map and Data Library]] on the 5th Floor of Robarts. Please make an effort to be on time; I'll be there before 10 to help you find the classroom.  

Please take a look at the [[https://q.utoronto.ca/courses/99251/files/folder/Handouts?preview=3670640][Workshop Handout]] before class tomorrow! You shouln't need to actually do the downloads unless you plan to work on your own computer, but it might be fun to do a bit of work in advance. 

I've also returned your reflection 1 -- I hope! -- please let me know if there are any issues.  

* Lost Charger?
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 317646
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/317646
:ORG_LMS_POSTED_AT: 2019-06-12T13:28:11Z
:END:

Hello everyone, I got this note Monday evening from a student i nanother class. I'm hoping this turns out to belong to one of you!

----------------

Hello Prof. Price,

I hope this email finds you well. 

Today (June 10th) I was working in the computer lab SS561, and found a charger cord. I saw on the front door that you teach the class that takes place in this lab earlier today (WDW235H1), so I thought it is possible that one of your students left this item behind. I hope you can reach out to your students and inquire if anyone left a charger behind - if someone thinks it is theirs, maybe have them email me with details about the charger (colour, type of device it is for, etc) so I can confirm ownership and get this item back to its rightful owner.

Best wishes,

Hila 

* Do the Reading Please!
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 428707
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/428707
:ORG_LMS_POSTED_AT: 2019-10-31T15:59:27Z
:END:
At *minimum*, please read the Drucker reading that is o n the syllabus for today: http://www.digitalhumanities.org/dhq/vol/5/1/000091/000091.html -- I hope we can discuss some of the ideas there.  


It's Hallowe'en! come in costume if you like!

* More about Drucker
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 429203
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/429203
:ORG_LMS_POSTED_AT: 2019-10-31T21:30:58Z
:END:

Come prepared especially to discuss especially and at least figures 1,2,7,14,17.  See you soon! 

Hoping to give you back your papers before then but need to stadardize the marks properly first.

* Proposal Clarifications: What's due tomorrow
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 428788
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/428788
:ORG_LMS_POSTED_AT: 2019-10-31T16:35:50Z
:END:
I think perhaps it doesn't appear to be completely clear what is due tomorrow; I reproduce here the instructions from the main assignment, which hopefully are clearer in isolation: 


1. A proposal describing, in 200 words or fewer, the object whose story you plan to tell: what it is; why it was banned, by whom, and in what historical context; and how you plan to shape your exhibit. *Due <2019-11-01 Fri>*

2. An annotated bibliography ([[http://advice.writing.utoronto.ca/types-of-writing/annotated-bibliography/]]) that contains: links to and descriptions of at least 3 things for your collection; references to and summaries of at least 3 *scholarly* sources (scholarly print books, scholarly journal articles, scholarly encyclopedia entries). *Due <2019-11-01 Fri>*

I hope that helps!!

* Notes for Today's class
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 312501
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/312501
:ORG_LMS_POSTED_AT: 2019-06-05T13:19:21Z
:END:

Oops, had hoped to write a more fulsome note but looks like I'm out of time. I've uploaded [[https://q.utoronto.ca/courses/99251/files/folder/Data%20visualization%20Files][a number of files to quercus for today's class]]. Exactly what they're for wil lbecome more evident later, I hope. 

Meanwhile, I have uploaded our texts to voyant tools to save you the trouble -- you can access them here: 
- [[https://voyant-tools.org/?corpus=f1e498d87d80d31a08eddee6087498a9][Les Mis as Corpus]]
- [[https://voyant-tools.org/?corpus=3850b9072e252c0284a555d978538a07][Frankenstein as Corpus]]
- [[https://voyant-tools.org/?corpus=263abefb0bb190230f8003e5ac16f5b8][Lady Susan as Corpus]]

* Late for office hours
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 458925
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/458925
:ORG_LMS_POSTED_AT: 2019-12-03T16:42:33Z
:END:

I'm sorry, I'm a bit late for office hours today due to an illness in my household. I should be there by 1220 at the latest.

* Handing in final assignment
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 459069
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/459069
:ORG_LMS_POSTED_AT: 2019-12-03T18:04:16Z
:END:

There have been a few questions about how to hand the assignment in -- I've updated the form so it now allows submission of a website URL and a text comment as well.  Please use that  form and submit the public view of the exhibit.

* Raptors Jubilee
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 319546
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/319546
:ORG_LMS_POSTED_AT: 2019-06-17T11:31:43Z
:END:

In the Middle Ages, it was common for royal anniversaries and other great celebrations to be accompanied by an amnesty for prisoners held in royal captivity. 

In accordance with this tradition, and in light of the Raptors victory in game 6, I can grant a *general extension* on the final assignment till Wednesday night, and I plan to cut class short today so that you can get to Nathan Philips Square in time to enjoy the end of the parade if you want.  

See you shortly!
* Handing in the final Assignment
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 320854
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/320854
:ORG_LMS_POSTED_AT: 2019-06-20T12:09:38Z
:END:
There have been several questions about handing in the final assignment, so I must not have been clear. Please hand in a word doc (or similar) at  [[https://q.utoronto.ca/courses/99251/assignments/170176][the assignment hand-in page]] containing:
- a link to your Omeka site (make sure the site has been made public, so I can see it!)
- your annotated bibliography

If you've already done this, don't worry about it! Congratulations on finishing and have a great summer!


* Grades due today
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 468227
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/468227
:ORG_LMS_POSTED_AT: 2019-12-13T16:57:34Z
:END:
For those of you with late work, my marks are due tomorrow. Please hand in everything you'd like to have marked by the end of the day Friday!

* Make sure you submit your project URL via Quercus
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 468235
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/468235
:ORG_LMS_POSTED_AT: 2019-12-13T17:17:52Z
:END:
A surprising number of projects are missing from Quercus. Please double-check to be sure you entered a URL there. You don't want a 0 in that assignment. 

* COMMENT get student list (for GH roster)

#+begin_src emacs-lisp
(let* ((students 
        (org-lms-get-students))
        (emails (cl-loop
         for s in students
         collect (plist-get s :email)))
        (students (cl-loop
                 for s in students
                 collect (plist-get s :name)))
       (num  (length emails)))
  
   num
   students
  )
#+end_src
