#+MACRO: ts (eval(mwp-get-ts+7  'org-mwp-classtimes-calibrate 2))
#+STARTUP: customtime
#+ORG_LMS_COURSEID: 127426
#+ORG_LMS_SECTION: announcement

* Welcome! And Website...
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 299852
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/299852
:ORG_LMS_POSTED_AT: 2019-05-05T17:56:42Z
:END:

Welcome, everyone, to WDW235! I'm looking forward to meeting you all very soon. 

I'm very much looking forward to this class, which I'll be teaching for the second time. I normally use lower-level tools than we'll be using in this course (that is, I tend to program in a text-based environment, rather than using these graphic user interfaces), so I'm looking forward to exploring some of these amazing DH projects with you. 

Quercus has been an immense improvement over Blackboard but for this class there are still a few missing pieces.  As a result, I am (for now at least) maintaining a *separate website* for HIS393. It can be found [[https://digitalhistory.github.io/wdw235/][on Github]], which incidentally is also a piece of infrastructure we will discuss in the course. 

There will be *many* more details forthcoming, both in class and on the website.  

See you in class!
 
* See you Tonight!
Hello everyone, I'm looking forward to meeting you all tonight.  

* Assignment 1
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 374399
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/374399
:ORG_LMS_POSTED_AT: 2019-09-12T14:18:57Z
:END:
Just a quick note that [[https://q.utoronto.ca/courses/127426/assignments/221044][the first assignment is now online]].  Please take a look before class today, and esp. look for any errors or confusion so I can correct them! 

* Lecture Notes; Assignment; Readings for Wednesday
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 301087
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/301087
:ORG_LMS_POSTED_AT: 2019-05-07T13:46:52Z
:END:
** Lecture Notes Fixed
 [[https://digitalhistory.github.io/wdw235/slides/01-intro][Slides from yesterday's lecture]] should now display more-or-less as expected; had some trouble w/ local images which has now been debugged :-) 

** Reflection Assignment 1
The Reflection assignment, which we will discuss more on Wednesday, is now up on both Quercus and [[https://digitalhistory.github.io/wdw235/assignment/][the course website]]. 

** Readings
We will *definitely* be taking time to discuss tomorrow's readings in class, so please make sure you actually read them.
- Miriam Posner's [[http://miriamposner.com/blog/how-did-they-make-that/][blog post]] discusses a number of projects -- please be sure to follow the (many) links whenever you can (some of them have aged a bit and are broken). Think about where your own interests lie.
- Ruecker & Galey's piece interweaves a numbrer of themes.  You yourself may not be especially interested in "how DH project should count when someone comes up for tenure", which is clearly one motivation of the essay, but the other themes will be relevant to many of you. You may find it a bit complex or convoluted, but please persevere.  You may find the going easier if you think about the following:
  - The discussion of design (pp. 405-07 and throughout) in many ways hinges on Winner's arguments in "Do Artifacts Have Politics", discussed on p. 406 and 407. Do you best to understand the main points. 
  - How should we understand the criteria for compelling arguments, which they summarize as "contestability, defensibility, and substantivity" (p.412ff)?
  - What do the authors mean when they suggest that digital objects can "reify an argument" (p.414)?
  - the [[http://www.textarc.org/PrintEditions.html][original TextArc]] is no longer live but [[http://vallandingham.me/textarc/][this cool partial replica]] can still be found ([[https://github.com/vlandham/textarc][code here]]) 

* Today's Class (<2019-09-19 Thu>)
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 384861
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/384861
:ORG_LMS_POSTED_AT: 2019-09-19T22:11:42Z
:END:

Today's class will be *much* less lecture-y, instead comprising a mix of discussion and workshopping.  Here's the approximate outline:

- discussion of today's readings, with an emphasis on [[http://muse.jhu.edu.myaccess.library.utoronto.ca/article/24448][deformance]]. Please spend some time thinking about the readings and any questions you might want to ask.  Consider the following:
  - why do the authors decide to use this new (made-up) word "deformance"?
  - what does this all have to do with technology (that is, why are we discussing here)? 
- workshopping with xml/xslt and TEI.  You will want to [[https://q.utoronto.ca/files/3647726/download?download_frd=1][read the handout]] and [[https://q.utoronto.ca/courses/99251/assignments/171001][the assignment]]
  - You'll need to [[http://fiddle.frameless.io/][navigate to the online xslt editor]] and paste in the code from the assignment.  

I think this will be fun today!   

* XML/TEI intro page!
I've published a page o n the website with some information about XML and TEI:

https://q.utoronto.ca/courses/127426/pages/introduction-to-xml-xslt-tei-and-html-long

Much of this is recapitulated in the handout, but we'll likely use this page a template for our lecture today, so you might want toread it. 

* Tonight: more deformance, more XML
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 393585
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/393585
:ORG_LMS_POSTED_AT: 2019-09-26T17:56:32Z
:END:

Hello everyone,

I wanted to let you know that tonight's class will be, in some ways, a rehash of last week at a higher level.  So 

- Make sure you've read the deformance piece this time! We'll discuss again. 
- I've put together a somewhat more realistic example of TEI and, incidentally, deformance.  You can [[https://titaniumbones.github.io/xslt-example/rj/rom-act2.xml][see it in action online here]], and you can [[https://github.com/titaniumbones/xslt-example/tree/master/rj][browse the actual code here]]. We will be  examining it in more detail tonight, and you may understand it a lot better if you look at it first. You can easily check it out by pasting the code into [[http://fiddle.frameless.io/][the XML fiddle site]], maybe using he "raw" view of [[https://raw.githubusercontent.com/titaniumbones/xslt-example/master/rj/rom-trans.xsl][the xsl stylesheet]] and [[https://raw.githubusercontent.com/titaniumbones/xslt-example/master/rj/rom-act2.xml][the full xml text]] to copy it more easily.  

* That last announcement
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 305537
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/305537
:ORG_LMS_POSTED_AT: 2019-05-16T15:45:23Z
:END:

it wasn't really an announcement, but a more detailed introduction to XML, XSLT, and HTML than we got in class. I'll distribute a bit more info soon -- maybe at the end of the day -- but I wanted to get this off ASAP so you could make use of it for you assignment!

* link to code
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 305014
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/305014
:ORG_LMS_POSTED_AT: 2019-05-15T16:09:25Z
:END:
[[https://hackmd.io/s/Bk0KFnYnE][here's the code for today]]

* Readings! Videos! Assignments! Discussions! Visits! Sign-ups!
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 400809
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/400809
:ORG_LMS_POSTED_AT: 2019-10-03T13:17:45Z
:END:
Hello Everyone,

This is a friendly reminder to you all to *do your work before class*. Tomorrow we'll be discussing these texts and videos: 
- William Noel, “[[http://www.ted.com/talks/william_noel_revealing_the_lost_codex_of_archimedes][Revealing the Lost Codex of Archimedes]]” (2012). [TED TALK]
- Bethany Nowviskie, “[[http://nowviskie.org/2014/anthropocene/][Digital Humanities in the Anthropocene]]”
- Eira Tansey, “[[http://eiratansey.com/2017/05/16/fierce-urgencies-2017/][When the Unbearable Becomes Inevitable: Archives and Climate Change]]” (2017).

*don't "forget" to read them!*

In addition, some announcements: 
- Really sorry about your assignments still not being marked.  Working on it! Some administrative confusion on my end.
- Some of you have been asking me about citation styles. I don't have strong preferences but I *do* strongly encourage you to use citation-management software, which will make your life *so much easier*. [[https://youtu.be/-hUxgC4EX2s][I recorded this short video introductio nto Zotero]] which I encourage you to watch.  
- You have hopefully started work on your second assignment. Good! If you're running into trouble, [[https://q.utoronto.ca/courses/127426/discussion_topics/400319][please use the discussion forum that I've set up for the assignment]]. And if you're feeling confident, perhaps head over to the discussion anyway to help your classmates out.
- Next week we'll be visiting the Fisher Rare Books Library. It will be really fun! The room we're using can only accomodate 20 students at a time, and the library closes at 8, so we will do this trip in *two separate groups* and potentially *end class an hour early* and bundle you off home for the holiday weekend (though I'll be around after 8 to answer questions). I've made a sign-up sheet which [[https://q.utoronto.ca/calendar?include_contexts=course_127426#view_name=week&view_start=2019-10-06][you can find in the course calendar on Quercus]]. Please use it! This is my first time making such a sign-up sheet, so I hope it works :-)

Enjoy the readings and see you in class!


* Omeka Login Instructions
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 400788
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/127426/discussion_topics/400788
:ORG_LMS_POSTED_AT: 2019-10-03T12:51:19Z
:END:
In this class we have a *shared login* to the local Omeka installation.  We'll talk more about protocols in class today. In this announcement, which should only be visible to the class, I'm giving you the login info: 

- Username: ~WDW235-2019-evening~
- Password: ~2019-evening~

Please feel free to login and look around before class, but *UNDER NO CIRCUNSTANCES MODIFY ANY RESOURCES THAT YOU FIND THERE.* Again, we'll learn how to use Omeka starting in class today. 

* Class *in Robarts* On June 3 -- PLEASE READ!!
Hello class,

I'm sorry this message did not go out last week as I intended -- I made  a technical error and have only just caught it.  

I realized rather belatedly that in order to do the planned activity tomorrow, we would need computers with the [[https://www.tableau.com/][tableau]] visualization software installed. It's not on the computers in our classroom, but it *is* on the Map & Data Library computers, so we will be shifting to *the same classroom we used 2 weeks ago on the 5th floor of Robarts*. We'll be there for the whole class, from 10-1. 

We'll be using a lightly-modified version of [[http://maps.library.utoronto.ca/workshops/IntroDataViz/index.php][the intro to datavisualization workshop materials]] provided by the MDL.  You may want to take a look at them. 

Please also see the [[https://digitalhistory.github.io/wdw235/syllabus/syllabus/][updated class schedule]], which will allow you to finish the 
I apologize for not sending this announcement out earlier

* Tomorrow's class -- PLEASE READ (also: Ref 1 assignment)
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 307088
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/307088
:ORG_LMS_POSTED_AT: 2019-05-22T00:03:58Z
:END:
I hope you all enjoyed your holiday weekend!

Tomorrow's class is *special* -- instead of meeting in our usual place we have the [[https://digitalhistory.github.io/wdw235/syllabus/syllabus/#6--data-openrefine][OpenRefine workshop]] in the [[https://mdl.library.utoronto.ca/][Map and Data Library]] on the 5th Floor of Robarts. Please make an effort to be on time; I'll be there before 10 to help you find the classroom.  

Please take a look at the [[https://q.utoronto.ca/courses/99251/files/folder/Handouts?preview=3670640][Workshop Handout]] before class tomorrow! You shouln't need to actually do the downloads unless you plan to work on your own computer, but it might be fun to do a bit of work in advance. 

I've also returned your reflection 1 -- I hope! -- please let me know if there are any issues.  

* Lost Charger?
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 317646
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/317646
:ORG_LMS_POSTED_AT: 2019-06-12T13:28:11Z
:END:

Hello everyone, I got this note Monday evening from a student i nanother class. I'm hoping this turns out to belong to one of you!

----------------

Hello Prof. Price,

I hope this email finds you well. 

Today (June 10th) I was working in the computer lab SS561, and found a charger cord. I saw on the front door that you teach the class that takes place in this lab earlier today (WDW235H1), so I thought it is possible that one of your students left this item behind. I hope you can reach out to your students and inquire if anyone left a charger behind - if someone thinks it is theirs, maybe have them email me with details about the charger (colour, type of device it is for, etc) so I can confirm ownership and get this item back to its rightful owner.

Best wishes,

Hila 


* Notes for Today's class
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 312501
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/312501
:ORG_LMS_POSTED_AT: 2019-06-05T13:19:21Z
:END:

Oops, had hoped to write a more fulsome note but looks like I'm out of time. I've uploaded [[https://q.utoronto.ca/courses/99251/files/folder/Data%20visualization%20Files][a number of files to quercus for today's class]]. Exactly what they're for wil lbecome more evident later, I hope. 

Meanwhile, I have uploaded our texts to voyant tools to save you the trouble -- you can access them here: 
- [[https://voyant-tools.org/?corpus=f1e498d87d80d31a08eddee6087498a9][Les Mis as Corpus]]
- [[https://voyant-tools.org/?corpus=3850b9072e252c0284a555d978538a07][Frankenstein as Corpus]]
- [[https://voyant-tools.org/?corpus=263abefb0bb190230f8003e5ac16f5b8][Lady Susan as Corpus]]
* Raptors Jubilee
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 319546
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/319546
:ORG_LMS_POSTED_AT: 2019-06-17T11:31:43Z
:END:

In the Middle Ages, it was common for royal anniversaries and other great celebrations to be accompanied by an amnesty for prisoners held in royal captivity. 

In accordance with this tradition, and in light of the Raptors victory in game 6, I can grant a *general extension* on the final assignment till Wednesday night, and I plan to cut class short today so that you can get to Nathan Philips Square in time to enjoy the end of the parade if you want.  

See you shortly!
* Handing in the final Assignment
:PROPERTIES:
:ORG_LMS_ANNOUNCEMENT_ID: 320854
:ORG_LMS_ANNOUNCEMENT_URL: https://q.utoronto.ca/courses/99251/discussion_topics/320854
:ORG_LMS_POSTED_AT: 2019-06-20T12:09:38Z
:END:
There have been several questions about handing in the final assignment, so I must not have been clear. Please hand in a word doc (or similar) at  [[https://q.utoronto.ca/courses/99251/assignments/170176][the assignment hand-in page]] containing:
- a link to your Omeka site (make sure the site has been made public, so I can see it!)
- your annotated bibliography

If you've already done this, don't worry about it! Congratulations on finishing and have a great summer!


* COMMENT get student list (for GH roster)

#+begin_src emacs-lisp
(let* ((students 
        (org-lms-get-students))
        (emails (cl-loop
         for s in students
         collect (plist-get s :email)))
        (students (cl-loop
                 for s in students
                 collect (plist-get s :name)))
       (num  (length emails)))
  
   num
   students
  )
#+end_src
