#+SETUPFILE: ./setup.org
#+HUGO_SECTION: assignment
#+ORG_LMS_SECTION: assignment
#+HUGO_MENU: :menu main :parent Assignments

* COMMENT Hugo Instructions
- Every exportable entry must have the ~EXPORT_FILE_NAME~ property set before export.


** Check out this elisp code if you're having trouble

#+begin_src emacs-lisp
(use-package ox-hugo-auto-export)

#+end_src

#+RESULTS:

* Overview
:PROPERTIES:
:EXPORT_FILE_NAME: overview
:END:

testing out the overview
 


* Participation :assignment:
:PROPERTIES:
:EXPORT_FILE_NAME: Participation
:PUBLISH:  nil
:ORG_LMS_EMAIL_COMMENTS: t
:ORG_LMS_CANVAS_COMMENTS: t
:DUE_AT: 2019-12-05
:GRADING_TYPE: letter_grade
:ASSIGNMENT_TYPE: canvas
:CANVAS_SUBMISSION_TYPES: (online_upload)
:ASSIGNMENT_WEIGHT: 0.15
:OL_PUBLISH: nil
:CANVASID: 259610
:CANVAS_HTML_URL: https://q.utoronto.ca/courses/127426/assignments/259610
:CANVAS_SUBMISSION_URL: https://q.utoronto.ca/courses/127426/assignments/259610/submissions?zip=1
:SUBMISSIONS_DOWNLOAD_URL: https://q.utoronto.ca/courses/127426/assignments/259610/submissions?zip=1
:GRADING_STANDARD_ID: nil
:END:

** Rubric :rubric:
- *Attendance* :: 
- *Active Participation* :: 
- *Grade* :: 
* Reflection 01: DH Project Profile :assignment:
:PROPERTIES:
:EXPORT_FILE_NAME: reflection-1-project-profile
:PUBLISH:  t
:DUE_AT: 2019-09-19
:GRADING_TYPE: letter_grade
:ASSIGNMENT_TYPE: canvas
:ASSIGNMENT_WEIGHT: 0.15
:CANVAS_SUBMISSION_TYPES: (online_upload)
:OL_PUBLISH: t
:BASECOMMIT: none
:CANVASID: 221044
:CANVAS_HTML_URL: https://q.utoronto.ca/courses/127426/assignments/221044
:CANVAS_SUBMISSION_URL: https://q.utoronto.ca/courses/127426/assignments/221044/submissions?zip=1
:SUBMISSIONS_DOWNLOAD_URL: https://q.utoronto.ca/courses/127426/assignments/221044/submissions?zip=1
:GRADING_STANDARD_ID: nil
:END:

Your first assignment is to profile a Digital Humanities project, analyzing its research aims, its form and content, its interface, technologies, and intended audience. You will learn how to navigate Digital Humanities projects, how to identify and evaluate different aspects of such projects, and how to analyze the kinds of knowledge and digital artifacts    generated by DH projects. *Write-up: 700 words plus screenshots*.

You may select any project you like from the syllabus or from one of the pages below:

- [[https://digitalhumanities.duke.edu/all-projects]] (please start here)
- [[https://eadh.org/projects]] 
- https://cdh.unc.edu/prsp-template/proj_init/
- https://digitalhumanities.berkeley.edu/projects
# - [[https://dhcommons.org/projects]] (Oops! Down right now!)

This project profile is not an essay; it is a short, 2-3 page report. You do not need to write a formal introduction, thesis, argument, or conclusion. You should only report on your observations, using the questions below as categories of analysis, each with its own heading. Not all categories and questions apply to all projects, so *do not feel obligated to respond to all of them*. Your project profile will be evaluated for [[http://www.artsci.utoronto.ca/newstudents/transition/academic/grading][accuracy, clarity, detail, quality of analysis, and insight]].


1. *Project:* What is the name of the project? Who are its primary authors? Be sure to include one or more links in the first paragraph of your assignment, so we can navigate quickly to the project itself. 

2. *Topic:* What is the project about? (Examples: What topic and historical period does it focus on? What texts or art works or other material does it collect, explain, map, or analyze? What questions is the project seeking to answer?)

3. *People & Institutions*: Who is the project leader? Who are their collaborators? What is the institution involved in the project's development? What are the granting bodies funding the projects? Is credit given to individual contributors? To what extent?

4. *Presentation & User Experience:* What is the “digital artifact” through which this project communicates its findings? A book? A game? A map? An edition? An archive? A tool? Another type of digital artifact?

   As a user external to the project, what steps did you take to explore the project? Can you understand how to read the project's data or how to use the tools it is building? As you explore the project, what do you find easy? What do you find difficult? What do you like? What do you dislike? Document your experience with screenshots, please ([[https://screenshots.firefox.com/][firefox's screenshot tool]] makes this very easy).

   Does this project provide access to users with e.g. limited bandwidth, minimal computing (e.g. smartphones instead of laptops), vision or hearing or tactile impairment?

5. *Data:*  What data does the project generate? What data format(s): text files, pdf files, digital images, databases, Excel or .csv files? Does the project provide narrative context for its data (that is, does it clearly explain what its data means and why it matters, for readers not familiar with the project)? Is access to project data open, subscription-only, or under a specific licence? May other scholars download the project's data?

6. *Technologies:* What technologies (encoding formats, digital publication platforms, software) are used in this project or built as part of this project? Are these technologies open-source, open-access?

7. *Audience:* Who is the intended audience for this project? That is, does this project primarily speak to laypeople? Scholars? Specialists? How can you tell?

8. *Limitations:* Does the project make note of any limitations in its work, any gaps or uncertainties in its data? Can you find limitations in its work---that is, gaps between its stated goals and its results?

This assignment is based on the [[https://dmptool.org/][DMP Tool]], the U of T DH Census Profile tool, and [[https://docs.google.com/document/d/1jp0bQ18hXKxekgACfBCw_6P6lO_xg4uzUXXMvT2jaPo/edit][Kristen Mapes]]' DH Project Critique assignment.

** Rubric :rubric: 
Components (check/no-check)
- [ ] topic
- [ ] people + institutions
- [ ] presentation + UX
- [ ] data
- [ ] technologies
- [ ] audience
- [ ] limitations


- *Grade* ::
- *Comments* :: 
* Reflection 02: The Ruin :assignment:
:PROPERTIES:
:EXPORT_FILE_NAME: reflection-2-the-ruin
:PUBLISH:  t
:DUE_AT: 2019-10-10
:GRADING_TYPE: points
:ASSIGNMENT_TYPE: canvas
:ASSIGNMENT_WEIGHT: 0.20
:CANVAS_SUBMISSION_TYPES: (online_upload)
:OL_PUBLISH: t
:ASSIGNMENT_TYPE: canvas
:BASECOMMIT: none
:GRADING_STANDARD_ID: nil
:ID:       831680db-1f4c-441a-9b5d-28d30066ae13
:CANVASID: 226000
:CANVAS_HTML_URL: https://q.utoronto.ca/courses/127426/assignments/226000
:CANVAS_SUBMISSION_URL: https://q.utoronto.ca/courses/127426/assignments/226000/submissions?zip=1
:SUBMISSIONS_DOWNLOAD_URL: https://q.utoronto.ca/courses/127426/assignments/226000/submissions?zip=1
:END:

Before completing this assignment, read the *recently revised, HTML version* of the handout “[[https://digitalhistory.github.io/wdw235/assignment/reflection-2-handout/][The Ruin: Digital Literary Studies]]” and carry out the exercises it asks you to do.

1. What is /The Ruin/? Briefly describe the poem and its themes. State what passage you are focusing on and analyze its poetic characteristics, as discussed in class. Be specific; cite poem by line numbers. Cite Echard's online translation correctly using the citation format of your choice.

2. What is “deformance,” as defined by McGann and Davidson, and how did you practice deformance on /The Ruin?/ Cite McGann and Davidson correctly using the citation format of your choice.

3. Describe the literary study methodology we used. Make sure you answer the following questions:

   1. What is TEI? How did we use it? (Your own words, please.)

   2. What tag did you create? What is it supposed to describe? Why did you choose it? Include at least one screenshot of the viewing screen with your TEI code, XSLT code, and results.

   3. What did you learn from making these digital artifacts that simply reading the poem did not uncover? What is the most significant affordance of your tools and digital artifacts that enabled you to gain these insights? What /failed/ to work---that is, what was difficult or counterproductive about working with TEI and XSLT?

   4. How does your analysis work /with/ or /against/ the poem---that is, are you “breaking” or “recreating” the poem? What difference does it make that you are reading an endangered poem---that is, a poem that comes down to us in fragments, in a single manuscript, in a language no longer spoken? Be as specific as possible.


** Evaluation 

This assignment is graded out of 20.

*** Intro (/4)

- A clear contextualization of /The Ruin/: its manuscript context, its historical period, and its content.

- A clear definition of “deformance” (McGann & Samuels).

*** TEI (/6)

- A clear definition of TEI in the students' own words is present (/2)

- Screenshots of TEI and XSLT code are present; output of the TEI and XSLT code is present (/2)

- Student invent their own XML tag, highlighting a consequential aspect of the poem (/2)

*** Analysis (/6)

- Discussion of imagery, stylistic devices, literary strategies, and thematics of the poem is present

- Students' observations are specific -- that is, observations could not apply to any Old English poem (“alliteration creates rhythm in the poem”) or to any text (“verbs describe the action in the poem”); instead, they point out characteristics of this particular poem.

- Using their own XML tag, students observe interesting poetic details and discuss these details' thematic effects

*** Clarity & Correctness (/4)

- Sentences are clear and vivid. Word usage, grammar, sentence structure, and punctuation are correct. Some informality is acceptable, as long as the reflection is clearly readable.

** Rubric 

- Grade :: 

| Part          | Score | out of | Comments |
|---------------+-------+--------+----------|
| Intro         |       |      4 |          |
| TEI           |       |      6 |          |
| Analysis      |       |      6 |          |
| Clear/Correct |       |      4 |          |

- General Comments :: 

* Reflection 02: Handout and Preliminary Exercises :assignment:
:PROPERTIES:
:PUBLISH:  nil
:CUSTOM_ID: the-ruin-digital-literary-studies
:EXPORT_FILE_NAME: reflection-2-handout
:CANVASID: 299511
:CANVAS_PAGE_URL: reflection-02-handout-and-preliminary-exercises
:CANVAS_HTML_URL: https://q.utoronto.ca/courses/127426/pages/reflection-02-handout-and-preliminary-exercises
:CANVAS_EDITING_ROLES: teachers
:END:
** 
In this assignment, you will *encode* parts of a thousand-year-old poem using a markup language, *display* the marked-up text in a web browser using a computational translator, and *discuss* this exercise using the idea of *deformance* as a guide.  This handout *should* contain everything you need to complete the assignment, but please use the discussion forum to ask any technical (or other!) questions.
** The Poem: “The Ruin” (from the tenth century Exeter Book), translated by Sian Echard, silently emended
   :PROPERTIES:
   :CUSTOM_ID: the-poem-the-ruin-from-the-tenth-century-exeter-book-translated-by-sian-echard-silently-emended
   :END:

 "[[http://faculty.arts.ubc.ca/sechard/oeruin.htm][The Ruin]]" was likely written in the 8th or 9th century, and recorded in the [[https://en.wikipedia.org/wiki/Exeter_Book][Exeter Book]] in the 10th century. The only surviving copy has a large burn down the centre of the page that renders parts of the poem illegible. (See [[https://sites.nd.edu/manuscript-studies/2017/11/20/ivory-in-the-rust-reading-the-old-english-ruin-in-south-bend][this blog post]] for a substantive discussion of the poem.)

#+CAPTION: /Exeter Cathedral Library MS 3501, f. 124r, all rights reserved Dean & Chapter Exeter Cathedral/
https://sites.nd.edu/manuscript-studies/files/2017/11/Fahey-Screen-Shot-2017-11-17-at-6.13.25-PM-768x585.png

*** Transcription
1. Wondrous is this wall-stead, wasted by fate.
2. Battlements broken, giant's work shattered.
3. Roofs are in ruin, towers destroyed,
4. Broken the barred gate, rime on the plaster,
5. walls gape, torn up, destroyed,
6. consumed by age. Earth-grip holds
7. the proud builders, departed, long lost,
8. and the hard grasp of the grave, until a hundred generations
9. of people have passed. Often this wall outlasted,
10. hoary with lichen, red-stained, withstanding the storm,
11. one reign after another; the high arch has now fallen.
12. The wall-stone still stands, hacked by weapons,
13. by grim-ground files.
14. ...
15. ...
16. ...
17. ...
18. Mind quickened ... and the artificer,
19. skilled in round-building, bound the wall-base,
20. wondrously with iron.
21. Bright were the halls, many the baths,
22. High the gables, great the joyful noise,
23. many the mead-hall full of pleasures.
24. Until fate the mighty overturned it all.
25. Slaughter spread wide, pestilence arose,
26. and death took all those brave men away.
27. Their bulwarks were broken, their halls laid waste,
28. the cities crumbled, those who would repair it
29. laid in the earth. And so these halls are empty,
30. and the curved arch sheds its tiles,
31. torn from the roof. Decay has brought it down,
32. broken it to rubble. Where once many a warrior,
33. high of heart, gold-bright, gleaming in splendour,
34. proud and wine-flushed, shone in armour,
35. looked on a treasure of silver, on precious gems,
36. on riches of pearl...
37. in that bright city of broad rule.
38. Stone courts once stood there, and hot streams gushed forth,
39. wide floods of water, surrounded by a wall,
40. in its bright bosom, there where the baths were,
41. hot in the middle.
42. Hot streams ran over hoary stone
43. into the ringed water where baths were
44. ...
45. ...
46. That was a noble thing, the house and the city.
** Deformance
   :PROPERTIES:
   :CUSTOM_ID: deformance
   :END:
We will discuss in class this [[https://en.wikipedia.org/wiki/Portmanteau][portmanteau]] term coined by Lisa Samuels and Jerome McGann, a combination of “deform” and “performance.” Be sure you have some grasp of what this means!


** Introduction to XML,XSLT, TEI, and HTML (!)
   :PROPERTIES:
   :CUSTOM_ID: introduction-to-tei
   :END:
[[https://cdrh.unl.edu/articles/basicguide/TEI][TEI]] is a [[https://en.wikipedia.org/wiki/Markup_language][markup language]] -- a system for annotating documents that can be read an processed by other compute programs.  It is a format, or defined feature set, of the [[https://www.w3schools.com/xml/xml_whatis.asp][XML]] "metalanguage", a very widely-used system for structuring and processing many kinds of data.  Digital humanists use TEI to turn literary texts into structured data that can be manipulated and queried in many ways, but especially on the web.  

The process of turning a TEI document into a visual representation on a screen is complex:
- first, the text must be *marked up* -- textual elements must be identified and annotated (we'll discuss how this works in more detail very soon).  This work can be both painstaking and tedious
- next, a *translation scheme must be written* that /processes/ the xml text into [[https://en.wikipedia.org/wiki/HTML][HTML]], the main language of the web. This translation is almost always written in a language called [[https://en.wikipedia.org/wiki/XSLT][XLST]] (which is itself a dialect of XML)
- finally, the translated document must be *displayed by a browser* that understands HTML, like Firefox or Chrome.   

Becasue this topic is so immense, we will not be producing fully TEI-compliant documents in this class -- instead, we will make TEI-like XML and process those docs into super-simple HTML documents.  

So, in order to complete this assignment, you must learn at least a tiny bit about *XML*, *XSLT*, and *HTML*.  That's a lot! I won't give you a systematic introduction to any of these systems; instead, this handout presents a very small amount of information on each, and gives some examples of how you might use them in the assignment. 

*** Viewing
   :PROPERTIES:
   :CUSTOM_ID: viewing
   :END:

To view/work with XML files, please navigate to either of these xml/xslt live editors:
- [[http://fiddle.frameless.io/][XML fiddle]] (this one at least has syntax highlighting, which makes the code a bit easier to read). 
- [[https://www.w3schools.com/xml/tryxslt.asp?xmlfile=cdcatalog&xsltfile=cdcatalog][W3 Schools]] (I don't like this one as much)


*Paste your XML poem into the left window of the editor.* Start with this code:  
#+begin_src xml
<?xml version="1.0" encoding="UTF-8"?>
<poem>
  <l n="1">This <concrete-noun>wall-stone</concrete-noun> is wondrous; fates broke it</l>
  <l n="2"><concrete-noun>courtyard pavements</concrete-noun> were smashed; the work of giants is decaying.</l>
  <l n="3"><concrete-noun>Roofs</concrete-noun> are fallen, ruinous <concrete-noun>towers</concrete-noun>,</l>
  <l n="4"> the frosty gate with frost on cement is ravaged, </l>
</poem>
#+end_src

*Paste your XSLT (your script for turning XML into HTML) into the right window of the browser.* Again, here is some starter code:

#+begin_src xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:template match="/">
    <html>
      <body>
        <h1>The Ruin</h1>
        <xsl:for-each select="poem/l/concrete-noun">
          <p> <xsl:value-of select="current()"/> </p>
        </xsl:for-each>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
#+end_src

*** XML Essentials: Tags & Structures

XML "marks up" elements of a text by surrounding bits of text with [[https://www.w3schools.com/xml/xml_syntax.asp][tags]]. The totality of ~<starting-tag>Content</end-tag>~ is called an [[https://www.w3schools.com/xml/xml_elements.asp][XML element]]. 

Take this example (stolen from [[https://www.w3schools.com/xml/xml_elements.asp][W3Schools]]): 
#+begin_src xml
  <book category="children">
    <title>Harry Potter</title>
    <author>J K. Rowling</author>
    <year>2005</year>
    <price>29.99</price>
  </book>
#+end_src

Here we have a *root element* called ~<book>~ which encloses several [[https://www.w3schools.com/xml/xml_tree.asp#midcontentadcontainer][child elements]] (~<title>~, ~<author>~, etc). Everything between ~<book category="children">~ and ~</book>~ is part of the ~<book>~ element.  In general, an element has the structure:

- opening tag: ~<tag>~
- content: text and child elements, which must be fully nexted within the parent (if an opening tag is inside the element, the closing tag must *also* be inside it
- closing tag: ~</tag>~ . Note the forward slash */* within the ~<>~ greater-than less-than signss.

Here's a trivial example that you might find in a TEI document:

#+begin_src  xml
<l>And then my lord <person>Yvain</person> arrived in <place>Camelot</place>.</l>
#+end_src

The tags here are "l", "person", and "place".

**** The XML declaration
:PROPERTIES:
:CUSTOM_ID: xml-dec
:END:

Every real XML document must also begin with an "XML Declaration" which identifies it as an XML document.  It will look like this: 

#+begin_src xml
<?xml version="1.0" encoding="UTF-8"?>
#+end_src

And a very simple full document will look like this:
#+NAME: simple-xml
#+begin_src xml
<?xml version="1.0" encoding="UTF-8"?>
<poem>
  <l n="1">This wall-stone is wondrous; fates broke it</l>
  <l n="2">courtyard pavements were smashed; the work of giants is decaying.</l>
  <l n="3">Roofs are fallen, ruinous towers,</l>
  <l n="4"> the frosty gate with frost on cement is ravaged, </l>
</poem>
#+end_src

*** Displaying XML with XSLT
A document that has been marked up with XML now has a structure that a computer can understand, which is great! But a web browser will not know how to display that document unless we give it instructions for *transforming* the XML structure into a language that the browser understands. We use XSLT for this purpose -- a special language that exists to manipulate XML documents.  

XSLT is complicated, and we will use just a tiny part of it.  We need to understand just a few concepts: 
- *stylesheet declaration* surrounds the rest of the XSLT document, identifying it as an XSLT instruction set
- *[[https://www.w3schools.com/xml/xsl_templates.asp][templates]]* give instructions for transforming particular XML elements
- *[[https://www.w3schools.com/xml/xpath_syntax.asp][Xpath Expressions]]* are used to tell the templates which elements to transform
- *value statements* insert the contents of an element into the final HTML product

**** Stylesheet Declaration
An XSLT Stylesheet always starts with an XML declaration and then an ~<xsl:stylesheet>~ tag; the document ends with the closing ~</xsl:stylesheet>~ tag:

#+begin_src xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<!-- Content of Stylesheet Goes Here!! -->

</xsl:stylesheet>
#+end_src

**** XSLT Templates

Inside the ~xsl:stylesheet~ we put all the ~xsl:template~ tags we need.  Each template is an instruction for dealing with a particular tag or set of tags.  So, if we use [[simple-xml][our simple XML file from above]] as the XML source, we might start by building an XSLT document like this:

#+begin_src xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:template match="/">
      <xsl:apply-templates/>
  </xsl:template>


  <xsl:template match="l">
    <p> <xsl:value-of select="."/> </p>
  </xsl:template>
</xsl:stylesheet>
#+end_src

What's happening here?  We have two templates. The first one "matches" the "root element", while the second one matches all the "l" elements. So if we read this document top to bottom, we might translate it this way: 
#+begin_example
I am an XML Document

Begin Stylesheet

   Begin Template for the root element
        Apply all Templates!
   End Template for the root elements

   Begin Template for each l element
        Return a line of code that reads:
        "<p> + content of the "l" element + </p>"
        (this creates one HTML paragraph for each "l" element in the original)
   End Template for the L Elements

End Stylesheet
#+end_example

Our original XML document is very simple, so we don't need much more than this. But as we'll see later, it can get much more complicated.  And in fact we can make it a little more sophisticated already by adding a bit more complexity: 

#+begin_src xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:template match="/">
    <body>
      <h1>Grand title</h1>
      <p>Let us begin our discussion of poetry here.</p>
          <xsl:apply-templates/>
    </body>
  </xsl:template>

  <xsl:template match="poem">
    <h2>The Ruin</h2>
          <xsl:apply-templates/>    
  </xsl:template>

  
  <xsl:template match="l">
    <p> <xsl:value-of select="."/> </p>
  </xsl:template>

</xsl:stylesheet>
#+end_src

Try to read the text and understand what's going on!

Now let's learn a little bit more about how the ~match~ and ~select~ attributes in the above code really work. 

**** Xpath Expressions
When we make templates with a ~match~ attribute, or use the ~value-of~ and ~apply-templates~ instructions (see below), we have to tell XSLT which XML elements we are talking about. The selection of elements is done using what are called "[[https://www.w3schools.com/xml/xpath_syntax.asp][Xpath Expressions]]". These are a way to describe the position of elements (sometimes called "nodes") in the XML document. The syntax is extemely complex, so we will just say a few things about it here: 

- "/" refers to the root element -- the element that contains all the other elements in the document
- ="/poem"= refers to a ~<poem>~ element *at the document root*, while "poem" refers to *any poem element in the document*.  So for instance, "l" will match all of our ~<l>~ elements, but ="/l"= *won't match anything,* because the existing ~<l>~ elements are all /inside the poem element/.
- "current()" and "." both refer to the *element that is being discussed at the present moment*. So, inside of ~<xsl:template match="poem">...</xsl:template>~, ~"."~ refers to the ~<poem>~ element.
- "@n" refers to the "attribute" *n*. I'll explain more about this in a second...

**** Value Statements (~value-of~ and ~apply-templates~)
We almost always want to get the value of the XML elements -- otherwise why would we do all this work? There are two ways to get that value...

***** [[https://www.w3schools.com/xml/ref_xsl_el_value-of.asp][xsl:value-of]]: the simple way
~<xsl:value-of select="."/>~ just grabs the content of the element and inserts it in the final output.  We don't use it much (see below for reasons), but it can be particularly helpful when we care about *attributes*.  So for instance, consider this line of XML: 

#+begin_src xml
<l n="2">courtyard pavements were smashed; the work of giants is decaying.</l>
#+end_src

Maybe we really care that this is line 2! Maybe we want to display those line numbers so readers understand what we're talking about! We can use the "@n" syntax we saw just above: 

#+begin_src xml
<xsl:value-of select="@n"/>
#+end_src

When this instruction is applied to the line above, it will return the number "2"!

***** [[https://www.w3schools.com/xml/xsl_apply_templates.asp][xsl:apply-templates]]: the better way (usually)
Most of the time, we use ~<xsl:apply-templates/>~ instead of ~<xsl:value-of select="."/>~.  This is because *we usually can't be sure that the element doesn't contain other elements.* And if we just use "value-of", then the elements inside our current element won't be properly translated.  "apply-templates" will check to see if any templates need to be applied internally, and then after those templates have been applied, it will return the whole resultant text.  

All of this is really helpful -- but since we're generating HTML, you *also* need to know a little bit of HTML to make the text look the way you want it to!
**** HTML Tags and attributes

I won't go into HTML in much depth -- there are many many /many/ resources available online.  Here we'll just describe a few very basic features. 

Like XML documents, HTML documents contain *elements* delimited by *tags*. Also like in XML, those tags can have *attributes* that give extra information.  Here are some tags you may want to use in your work:

#+begin_src html
<html>
  <body>
    Every HTML document should start with a "html" tag and include a "body" tag inside it.

    <h1>first-level header</h1>
    <h2>second=level header</h2>
    (etc up to "h6")
    <p>
      paragraph containing <strong>bold</strong> and <em>italic</em> text.
      Paragraphs can also contain
      <span>
        tags, which don't do anything by default...
        but wait!
      </span>
    </p>
    <p style="color;white;background-color:red;border:2px solid black; padding: 10px;">
      This paragraph will have white text, a red background, a black border,
      and lots of space around it. Meanwhile, this
      <span style="color:red;background-color:green">
        will be entirely invisible to red-green colorblind readers.
      </span>  
    </p>

    <table>
      <tr>
        <td>this is a </td>
        <td>table with</td>
        <td>1 row and 3 columns</td>
      </tr>
    </table>

    
  </body>
</html>
#+end_src
- *p* tags are paragraphs
- *h1, h2... h6* tags are headers
- *span* tags delineate text within a paragraph
- *strong* and *em* do bold and italics
- You can build tables using the somewhat complicated syntax above
- you can set style attributes using the "style=" commands as you see them above; I've shown a few possibilities but there are literally hundreds more.  

Hopefully this should be enough for you to get started!
*** Learn more

The [[https://developer.mozilla.org][Mozilla Developer Network]] is the best starting point for almost all technical topics related to the web.  The [[https://developer.mozilla.org/en-US/docs/Web/XML/XML_introduction][XML Introduction]], [[https://developer.mozilla.org/en-US/docs/Web/XSLT][XSLT Intro]], and [[https://developer.mozilla.org/en-US/docs/Web/HTML][much more extensive HTML information]] are all very helpful, and contian links to further information. 

The [[https://tei-c.org/][TEI website]] has extensive information about the TEI standard, but is extremely technical. [[http://teibyexample.org/modules/TBED04v00.htm][TEI By Example]] can be quite helpful, but again, is very detailed.  The full text of /[[https://books.openedition.org/oep/426][What is the Text Encoding Initiative]]/ is available online and may also be helpful. The University of Nebraska's  [[https://cdrh.unl.edu/articles/basicguide][Basic Guide to Text Encoding]] is a lightweight introduction that may be easier to follow than any of the above!

** Reading Hints
   :PROPERTIES:
   :CUSTOM_ID: reading
   :END:

- Content: Read your passage. Flag any parts that are unclear or mysterious or confusing. Summarize its content in one sentence.
- Style: Look for:
   - verbal patterns (e.g. sentences with the same shape) : what are they? What is their effect?
   - sensory imagery (e.g. references to what you can see, hear, touch, feel): any patterns? What do they do for the poem?
- Theme: if you had to summarize the theme of your passage in one word, what would that word be? How does style support or embody theme?
** Encoding
   :PROPERTIES:
   :CUSTOM_ID: encoding
   :END:

*Choose one of the following passages:* 1-15; 16-31a; 31b-46.

Encode your passage using the following TEI tags:

- *Lines and line numbers*

#+begin_src xml
 <poem>
   <l n=″1″>This masonry is wondrous; fates broke it</l>
</poem>
#+end_src

- *At least one made-up tag of your own, specific to the poem*

#+begin_src xml
<concrete_noun> wall-stone </concrete_noun>
<adjective> wondrous </adjective>
<colour>golden</colour>
<poetic-formula>the work of giants</thew
#+end_src

** Encoding Discussion
   :PROPERTIES:
   :CUSTOM_ID: encoding-discussion
   :END:

What is your made-up tag(s)? How is this tag supposed to work, within this poem and more generally? Why is it useful?

After encoding, what additional characteristics of the poem, if any, did you notice in terms of verbal patterns, sensory imagery, or the development of the poem's themes?

** Appendix: More Complex Example
   :PROPERTIES:
   :CUSTOM_ID: appendix-more-complex-example
   :END:

It may help you to see a few more tags. Here is a slightly more complex example, with a more completely marked-up selection of the poem. I have *not* annotated this example, but it showcases a few more features of the systems we're learning.  In particular, this example introduces:
- [[https://www.w3schools.com/cssref/css_colors_legal.asp][more complex colors]]
- [[https://www.w3schools.com/tags/tag_a.asp][the "a" or hyperlink tag]]
- [[https://stackoverflow.com/questions/10395488/how-to-concat-a-string-to-xslvalue-of-select][curly braces as a shortcut for xpaths]]
- [[https://stackoverflow.com/questions/11744465/xpath-difference-between-node-and-text][the somewhat confusing xpath test "node"]], which sometimes makes sense to use when "current()" doesn't produce the effect you want.
 
#+begin_src xml
<?xml version="1.0" encoding="UTF-8"?>
<poem>
  <l n="1">This <concrete-noun>wall-stone</concrete-noun> is <adjective>wondrous</adjective>; <hyperbole>fates broke it</hyperbole></l>
  <l n="2"><concrete-noun>courtyard pavements</concrete-noun> were smashed; the <concrete-noun>work</concrete-noun> of <concrete-noun>giants</concrete-noun> is decaying.</l>
  <l n="3"><concrete-noun>Roofs</concrete-noun> are fallen, ruinous <concrete-noun>towers</concrete-noun>,</l>
  <l n="4"> the frosty <concrete-noun>gate</concrete-noun> with <concrete-noun>frost</concrete-noun> on <concrete-noun>cement</concrete-noun> is <hard-word>ravaged</hard-word>, </l>
</poem>
#+end_src

#+begin_src xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:template match="/">
    <html>
      <body>
        <h1>The Ruin</h1>
        <table>
          <xsl:apply-templates select="node()"/>
        </table>
      </body>
    </html>
  </xsl:template>

  <xsl:template match="poem">
    <table>
      <xsl:apply-templates select="node()"/>
    </table>
  </xsl:template>

  <xsl:template match="l">
    <tr>
      <td style="padding-right:10px; color:gray">
        <xsl:value-of select="@n"/>
      </td>
      <td style="color:white;">
        <xsl:apply-templates select="node()"/>
      </td>
    </tr>
  </xsl:template>

  <xsl:template match="concrete-noun">
    <strong style="color:black;">
      <xsl:apply-templates select="node()"/>
    </strong>
  </xsl:template>
  <xsl:template match="adjective">
    <span style="color:green">
      <xsl:apply-templates select="node()"/>
    </span>
  </xsl:template>

  <xsl:template match="hyperbole">
    <span style="background-color: rgba(250,20,20,0.3)">
      <xsl:apply-templates select="node()"/>
    </span>
  </xsl:template>

  <xsl:template match="hard-word">
    <a style="background-color: rgba(20,250,20,0.3)" href="https://www-oed-com.myaccess.library.utoronto.ca/search?q={current()}">
      <xsl:apply-templates select="node()"/>
    </a>
  </xsl:template>

</xsl:stylesheet>

#+end_src
* Reflection 03: Data visualization Comparison :assignment:
:PROPERTIES:
:EXPORT_FILE_NAME: reflection-3-data-visualization
:PUBLISH:  t
:DUE_AT: 2019-11-28
:GRADING_TYPE: points
:ASSIGNMENT_TYPE: canvas
:ASSIGNMENT_WEIGHT: 0.10
:CANVAS_SUBMISSION_TYPES: (online_upload)
:OL_PUBLISH: t
:PUBLISH: t
:BASECOMMIT: none
:GRADING_STANDARD_ID: nil
:CANVASID: 250846
:CANVAS_HTML_URL: https://q.utoronto.ca/courses/127426/assignments/250846
:CANVAS_SUBMISSION_URL: https://q.utoronto.ca/courses/127426/assignments/250846/submissions?zip=1
:SUBMISSIONS_DOWNLOAD_URL: https://q.utoronto.ca/courses/127426/assignments/250846/submissions?zip=1
:END:

In approximately 600-800 words, briefly discuss the *Tableau* software we used in the Data Visualization workshop, considering in particular its uses and limitations when it comes to *dealing with humanities data* (remember [[http://www.digitalhumanities.org/dhq/vol/5/1/000091/000091.html][Johanna Drucker's essay on graphical display in the humanities!]]).  Be sure to address the following categories:

- briefly introduce the tool, describing its main features and uses
- Assess the tool's usability, and describe its principal user base
- describe the *characteristics of the data Tableau can make use of*, and any limitations on that data
- describe the *kinds of output* that Tableau produces, and again, any limitations
- Does the tool make hidden assumptions about the nature of knowledge, and do we learn anything form making those assumptions explicit? (Here it may be particularly useful to refer to Drucker's essay.)
- How might you make use of this tool in your own work *as a digital humanist*? Give a hypothetical example, in as much detail as you can muster. 

** COMMENT Rubric *rubric* 
- *Grade* ::
- *Comments* :: see inline
* Final Project: Consultation                                    :assignment:
:PROPERTIES:
:EXPORT_FILE_NAME: consultation
:PUBLISH:  t
:DUE_AT: 2019-10-25
:GRADING_TYPE: pass_fail
:ASSIGNMENT_TYPE: other
:ASSIGNMENT_WEIGHT: 0.01
:CANVAS_SUBMISSION_TYPES: (none)
::OL_PUBLISH: nil
:BASECOMMIT: none
:GRADING_STANDARD_ID: nil
:CANVASID: 233039
:CANVAS_HTML_URL: https://q.utoronto.ca/courses/127426/assignments/233039
:CANVAS_SUBMISSION_URL: https://q.utoronto.ca/courses/127426/assignments/233039/submissions?zip=1
:SUBMISSIONS_DOWNLOAD_URL: https://q.utoronto.ca/courses/127426/assignments/233039/submissions?zip=1
:OL_PUBLISH: nil
:END:

** Rubric                                                           :rubric:
- *Grade:*
* Final Project: Proposal :assignment:
:PROPERTIES:
:EXPORT_FILE_NAME: book-project-proposal
:PUBLISH:  t
:DUE_AT: 2019-11-01
:GRADING_TYPE: letter_grade
:ASSIGNMENT_TYPE: canvas
:ASSIGNMENT_WEIGHT: 0.09
:CANVAS_SUBMISSION_TYPES: (online_upload)
:OL_PUBLISH: t
:BASECOMMIT: none
:GRADING_STANDARD_ID: nil
:CANVASID: 233042
:CANVAS_HTML_URL: https://q.utoronto.ca/courses/127426/assignments/233042
:CANVAS_SUBMISSION_URL: https://q.utoronto.ca/courses/127426/assignments/233042/submissions?zip=1
:SUBMISSIONS_DOWNLOAD_URL: https://q.utoronto.ca/courses/127426/assignments/233042/submissions?zip=1
:END:

Please use this page to hand in your project proposals. For a description of the assignment, see the main project assignment page. 

** Rubric :rubric:
- Description of book and ban ::
- Feasibility of Project ::
- Style & Grammar  ::
- *Grade* :: 
* Final Project: Book Exhibit :assignment:
:PROPERTIES:
:PUBLISH:  t
:DUE_AT: 2019-12-04
:GRADING_TYPE: letter_grade
:ASSIGNMENT_TYPE: canvas
:ASSIGNMENT_WEIGHT: 0.35
:CANVAS_SUBMISSION_TYPES: (online_upload)
:OL_PUBLISH: t
:BASECOMMIT: none
:GRADING_STANDARD_ID: nil
:EXPORT_FILE_NAME: book-project-assignment
:CANVASID: 233045
:CANVAS_HTML_URL: https://q.utoronto.ca/courses/127426/assignments/233045
:CANVAS_SUBMISSION_URL: https://q.utoronto.ca/courses/127426/assignments/233045/submissions?zip=1
:SUBMISSIONS_DOWNLOAD_URL: https://q.utoronto.ca/courses/127426/assignments/233045/submissions?zip=1
:END:
** Overview
   :PROPERTIES:
   :CUSTOM_ID: overview
   :END:

In this assignment, you get to tell the story of a banned book you have seen in person, either from the Thomas Fisher Rare Book Library or from our list.

You will create a website that features a digital collection and exhibit about that book, using the free, open-source content management platform Omeka. Like a good museum curator, you will bring together a gallery of exciting pictures, and you will guide your visitors through that gallery through a well-researched, interesting narrative about your book.

- Your digital collection will catalogue evidence about your book: photographs of the book itself (title page, illustrations, marginal annotations, damage, other interesting features); images of related books from other museums; manuscript illuminations; other relevant multimedia. Each object of your digital collection will be described systematically, as books are described in a library catalogue.

- Your exhibit will be a guided tour about your book and the circumstances under which it was banned.

- You will use some digital technology as part of this assignment.

This is a scaffolded assignment: that is, you will produce several components at each stage, and each component builds on the ones before it-- like LEGO, except you get to build your own bricks.

** Learning Goals
   :PROPERTIES:
   :CUSTOM_ID: learning-goals
   :END:

By the end of this learning module, you will have learned:

- How to understand your book's significance, history, and meaning, in its historical context;

- How to think about the transmission and attempted restriction of knowledge in different technological platforms (manuscripts, printed books, digital media)

- How to build an exhibit around objects and their history;

- What metadata is, and why metadata matters

- What Omeka is, and what content management systems are
  
- How to create your own Omeka site: building items, creating digital collections and building exhibits featuring scholarly materials
  
** What You Hand In:
   :PROPERTIES:
   :CUSTOM_ID: what-you-hand-in
   :END:

1. A proposal describing, in 200 words or fewer, the object whose story you plan to tell: what it is; why it was banned, by whom, and in what historical context; and how you plan to shape your exhibit. *Due <2019-11-01 Fri>*

2. An annotated bibliography ([[http://advice.writing.utoronto.ca/types-of-writing/annotated-bibliography/]]) that contains: links to and descriptions of at least 3 things for your collection; references to and summaries of at least 3 *scholarly* sources (scholarly print books, scholarly journal articles, scholarly encyclopedia entries). *Due <2019-11-01 Fri>*

3. A complete digital exhibit website that contains your collection of objects and a narrative about that collection. For reference, a former student's UofT Library Research Prize-winning example of such a digital exhibit is described in detail here: [[https://tspace.library.utoronto.ca/handle/1807/88308][Jaya Thirugnanasampanthan's exhibit on /Thirteen Reasons Why/'s banning in the U.S.]] (you will have to click through a bit to find [[https://play.library.utoronto.ca/download/XPYcIMVV80N4][a link to a walkthrough of the site]]).

** Proposal
   :PROPERTIES:
   :CUSTOM_ID: proposal
   :END:

*100-200 words*: describe your book and the structure of your exhibit.

*Sample Proposal*

| *Example*                                                               | *Discussion*                                 |
|-------------------------------------------------------------------------+----------------------------------------------|
| My exhibit focuses on Ana Blandiana's /Întâmplări de pe strada mea/     | One sentence identifying your object and     |
| (‘Events From My Street'), a Romanian children's book, which was banned | its place/time of origin.                    |
| in Romania during the Ceaușescu regime.                                 |                                              |
|                                                                         |                                              |
| I will discuss this book from the following points of view:             | An overview of your exhibit: its sections    |
|                                                                         | and some of its objects.                     |
|                                                                         |                                              |
| *Book* I will describe the book itself, published in 1988 and banned    | Describe the book itself.                    |
| shortly afterwards.                                                     |                                              |
|                                                                         |                                              |
|                                                                         |                                              |
|                                                                         |                                              |
|                                                                         |                                              |
| *Ban or Challenge*. I discuss why the book was scrutinized by the       | You will probably have less to say in your   |
| Communist regime. Some items here include: photos of the pages with the | proposal: that is FINE. Indicate who banned  |
| poem “A star on my street,” a poem about a boastful kitten which was    | the bool, and why, and how your exhibit will |
| interpreted as a criticism of the dictator Ceausescu and caused the     | show this.                                   |
| book to be scrutinized by the Securitate (the secret police); archival  |                                              |
| photos of schoolchildren forced to celebrate Ceausescu; and children's  |                                              |
| textbooks featuring first-page photographs of Ceausescu. These          |                                              |
| artifacts show how official culture sought to frame and control the     |                                              |
| experience and knowledge of childhood.                                  |                                              |
|                                                                         |                                              |
| *Conclusion.* I discuss children's literature in Communist Romania as   |                                              |
| a space in which writers dared to experiment, because children's books  |                                              |
| allowed writers to say uncomfortable things in playful or disguised     |                                              |
| ways.                                                                   |                                              |
|                                                                         |                                              |
|                                                                         |                                              |
| I contrast this with the ways the contemporary school system, in their  |                                              |
| censorship of e.g. history books, competed to shape children's worlds   |                                              |
| and knowledge, selecting the literature and history curriculum to       |                                              |
| reflect the ideology of the totalitarian government.                    |                                              |
|                                                                         |                                              |

** Collection
   :PROPERTIES:
   :CUSTOM_ID: collection
   :END:

*5 Items or more, to be described with Dublin Core metadata, including photos of your book:*

The collection is a set of at least 5 items that document your book and the context in which it was banned. Photographs of the book should be taken by yourself; the other photographs, you may find on museum websites and cite properly.

Some examples of objects that shed light on your book and the context in which your book was banned:

- If you are studying a book banned in Nazi Germany, find digitized archival photographs documenting e.g. book burnings in Nazi Germany;

- If you are studying a book banned by the Catholic Church, photograph the Index;

- If you are studying, say, Darwin's /Origin of Species/, you can document its impact with photos of 19^{th} century newspaper articles about it...or with 21^{st} century newspaper articles on the controversy around the depiction and teaching of evolution vs. creationism in U.S. schools

- If you are studying a science book, you can illustrate the science of the day with museum pictures of relevant scientific instruments (microscopes, telescopes);

- If you are studying a book of saints' lives (banned by Protestants) or a theological work (attacking the Catholic Church), you may look for contemporary images of e.g. book burnings, anti-Papal posters, etc.

** Exhibit

In every exhibit, at least four sections are mandatory: *Introduction*; */Book/*; *Context*; and *Insights*. You may include other sections if needed.

*** Introduction

This section is a summary of your exhibit, indicating what your book is, when it was banned, and why. 100-150 words. (A cleaned-up version of your proposal.)

*** Book

In this section, you describe your book and its author. What is its title? Who is its author? In detail and in your own words, summarize what the book is about. (size; shape; damage; marginal annotations, if any; illustrations, if any; other distinguishing marks, if any.) Your items in this section can be different photos of your book. Include as much descriptive detail as you can.

*** Context

In this section, you describe the social and historical context of your book: that is, the book's *time*, *place*, and *purpose*. When and where was it written? What text technologies were involved in its creation? To what effect? Who was its intended audience? Why is the book in danger? If it is a banned or censored book, then who banned or challenged the book, and why? How was this censorship or challenge enforced? Your exhibit items can include maps, photographs of people reading the book, photographs of people destroying the book, recordings, etc.

*** Insights

What insights (specific to your book---not a general conclusion that almost any other banned or endangered book could illustrate) into text technologies and the transmission of knowledge would you like your viewer to draw from your exhibit?

More specifically: how do the cultural and technical conditions in which the book was produced affect its endangerment and its afterlife? And how does the digital exhibit help you reflect on the text culture of your book?

Draw on the scholarly readings of this course, from Alan Liu to Bethany Nowviskie, to discuss the “new media encounter” moment between the endangered book and your presentation of it in a digital medium. (Some things to think about: textual stability, deformance, sustainability, new media encounters, deep time...)

*** Works Cited

This section contains resources---scholarly articles or museum articles or books---on which your exhibit draws. You may use any scholarly citation style you like, as long as you are consistent.

Example:

Gogata, Cristina. “Parallel Libraries Of The Former Securitate. Ana Blandiana, ‘Intamplari De Pe Strada Mea' (‘Events From My Street').” Studia Universitatis Babes-Bolyai. 61(2): 2006, pp. 97-100.

/Happy researching!/

** Books
   :PROPERTIES:
   :CUSTOM_ID: books
   :END:

You will select the book from the list below. If there is a book you would like to cover that is not on the list, please come talk to me and/or Augustine *well ahead* of the proposal deadline. No more than three students per book, please.

Books from the Thomas Fisher Rare Book Library (use these specific editions, please):

1. Martin Luther. /Piae ac doctae in psalmos operationes/. Basileae: Adamus Petri, 1521.

2. Judah ben Samuel. /Sefer ha hasidim/. Bolonya: Avraham ha-Kohen b.k.mo.ha-r. Mosheh ha-Kohen, 5298 (1537/1538 CE).

3. Nicholas Copernicus. /De revolutionibus orbium coelestium./ Basileae: Ex Officina Henricpetrina, 1566.

4. Johannes Kepler. /Epitome astronomiae Copernicanae/. Lentijs ad Danubium: Excudebat J. Plancus, 1618-22.

5. /The Holy Bible: Containing the Old and New Testaments./ London: Robert Barker, 1631.

6. Galileo Galilei. /Dialogo sopra I due massimi sistemi del mondo tolemaico e copernicano./ In Fiorenza: B. Landini, 1632.

7. Albertus Magnus. /De secretis mulierum. Item de virtutibus herbarum, lapidum et animalium./ (Of the secrets of women. Also about the virtues of herbs, stones, and animals. [magic])

8. Charles Darwin. /On the Origin of Species/. London: J. Murray, 1859.

9. Sigmund Freud. /Vorlesungen zur Einfuehrung in die Psychoanalyse/. Leipzig und Wien: H. Heller, 1916-1917.

10. Niccolo Machiavelli. /Princeps/. Basiliae, 1589.

11. Rene Descartes. /Les meditations metaphysiques./ Paris: La veuue I. Camvsat, et P. le Petit, 1647.

12. John Milton. /Pro populo Anglicano defensio/. Londini: Typis Du Gardianis, 1651.

13. John Locke. Essay Concerning Human Understanding. London: Printed by Eliz. Holt, for Thomas Basset, 1690.

14. David Hume. /Philosophical Essays Concerning Human Understanding./ London: Printed for A. Millar, 1749.

15. John Wilkes. /The North Briton/, No. XLV. London, 23 April 1763.

16. Voltaire. /Dictionnaire philosophique./ 1765.

17. Thomas Paine. /The Rights of Man./ London: Printed for J.S. Jordan, 1791-2.

18. Karl Marx and Friedrich Engels. /The Manifesto of the Communist Party/. Vancouver: Whitehead Estate, 1919.

19. Dante Alighieri. /La commedia./ Vinegia: Petrus de Plasiis, Cremonensis, dictus Veronensis/,/ 18 Nov., 1491.

20. Geoffrey Chaucer. /The Canterbury Tales./ London: Printed by [R. Grafton for] Wyllyam Bonham, 1542.

21. Giovanni Boccaccio. /Il Decameron./ In Vinezia: Per li Giunti di Frienze, 1585.

22. Nathaniel Hawthorne. /The Scarlet Letter./ Boston: Ticknor, Reed, and Fields, 1850.

23. Walt Whitman. /Leaves of Grass/. Brooklyn, 1856.

24. George Eliot. /Adam Bede/. Edinburgh: W. Blackwood, 1859.

25. Victor Hugo. /Les miserables/. Bruxelles: A. Lacroix, Verboeckhoven, 1862.

26. Mark Twain. /Adventures of Tom Sawyer./ Toronto: Belford Bros., 1876.

27. Aristophanes. /Lysistrata/. Sydney: Fanfrolico Press, 1925.

** Useful Resources

/Reference Works:/

- American Library Association. [[http://www.ala.org/advocacy/bbooks][Banned and Challenged Books]].

- Carefoote, Pearce J, and Alberto Manguel. /Nihil Obstat: An Exhibition of Banned, Censored & Challenged Books in the West, 1491-2000; Exhibition and Catalogue/. Toronto: University of Toronto Library, 2005. Print.

- /Censorship: 500 Years of Conflict/. New York, N.Y: Oxford University Press, 1984. Print.
- [[http://www.oxfordbibliographies.com.myaccess.library.utoronto.ca/view/document/obo-9780199791286/obo-9780199791286-0015.xml][Censorship]] (Oxford Bibliographies Online).

/Book & Image Repositories:/

- [[https://www.bl.uk/victorian-britain][British Library]]

- [[http://www.britishmuseum.org/research/collection_online.aspx][British Mueum]]

- [[https://dp.la/][Digital Public Library of America]]

- [[http://digital.bodleian.ox.ac.uk/][Digital Bodleian]]

- [[http://art.thewalters.org/browse/category/manuscript-and-rare-books/][Walters Art Museum]]

- [[http://www.metmuseum.org/art/collection][Metropolitan Museum in New York]]

- [[http://www.mfa.org/collections][Museum of Fine Arts Boston]]

** Rubric                                                           :rubric: 
- *Grade* ::
- Comments :: 
* Paper Assignment 1
* COMMENT Local Variables                          
# Local Variables:
# org-hugo-auto-export-on-save: t
# End:
