((Participation :courseid "127426" :canvasid nil :due-at nil :html_url nil :name "Participation" :submission_type "online_upload" :published nil :submission_url nil :basecommit nil :org_lms_email_comments nil :org_lms_canvas_comments nil :grade_type "letter_grade" :assignment-type nil :directory "participation" :rubric "- *Grade* :: ") (Reflection01:DHProjectProfile :courseid "127426" :canvasid "221044" :due-at "2019-09-19" :html_url "https://q.utoronto.ca/courses/127426/assignments/221044" :name "Reflection 01: DH Project Profile" :submission_type "online_upload" :published "t" :submission_url "https://q.utoronto.ca/courses/127426/assignments/221044/submissions?zip=1" :basecommit "none" :org_lms_email_comments nil :org_lms_canvas_comments nil :grade_type "letter_grade" :assignment-type "canvas" :directory "reflection-01:-dh-project-profile" :rubric "Components (check/no-check)
- [ ] topic
- [ ] people + institutions
- [ ] presentation + UX
- [ ] data
- [ ] technologies
- [ ] audience
- [ ] limitations


- *Grade* ::
- *Comments* :: ") (Reflection02:TheRuin :courseid "127426" :canvasid "226000" :due-at "2019-10-10" :html_url "https://q.utoronto.ca/courses/127426/assignments/226000" :name "Reflection 02: The Ruin" :submission_type "online_upload" :published "t" :submission_url "https://q.utoronto.ca/courses/127426/assignments/226000/submissions?zip=1" :basecommit "none" :org_lms_email_comments nil :org_lms_canvas_comments nil :grade_type "letter_grade" :assignment-type "canvas" :directory "reflection-02:-the-ruin" :rubric nil) (Reflection02:HandoutandPreliminaryExercises :courseid "127426" :canvasid "299511" :due-at nil :html_url "https://q.utoronto.ca/courses/127426/pages/reflection-02-handout-and-preliminary-exercises" :name "Reflection 02: Handout and Preliminary Exercises" :submission_type "online_upload" :published nil :submission_url nil :basecommit nil :org_lms_email_comments nil :org_lms_canvas_comments nil :grade_type "letter_grade" :assignment-type nil :directory "reflection-02:-handout-and-preliminary-exercises" :rubric nil) (Reflection03:DatavisualizationComparison :courseid "127426" :canvasid "169214" :due-at "2019-06-10" :html_url "https://q.utoronto.ca/courses/99251/assignments/169214" :name "Reflection 03: Data visualization Comparison" :submission_type "online_upload" :published "t" :submission_url "https://q.utoronto.ca/courses/99251/assignments/169214/submissions?zip=1" :basecommit "none" :org_lms_email_comments nil :org_lms_canvas_comments nil :grade_type "letter_grade" :assignment-type "canvas" :directory "reflection-03:-data-visualization-comparison" :rubric nil) (FinalProject:Consultation :courseid "127426" :canvasid "233039" :due-at "2019-10-25" :html_url "https://q.utoronto.ca/courses/127426/assignments/233039" :name "Final Project: Consultation" :submission_type "online_upload" :published nil :submission_url "https://q.utoronto.ca/courses/127426/assignments/233039/submissions?zip=1" :basecommit "none" :org_lms_email_comments nil :org_lms_canvas_comments nil :grade_type "letter_grade" :assignment-type "other" :directory "final-project:-consultation" :rubric "- *Grade:*") (FinalProject:Proposal :courseid "127426" :canvasid "233042" :due-at "2019-11-01" :html_url "https://q.utoronto.ca/courses/127426/assignments/233042" :name "Final Project: Proposal" :submission_type "online_upload" :published "t" :submission_url "https://q.utoronto.ca/courses/127426/assignments/233042/submissions?zip=1" :basecommit "none" :org_lms_email_comments nil :org_lms_canvas_comments nil :grade_type "letter_grade" :assignment-type "canvas" :directory "final-project:-proposal" :rubric "- Description of book and ban ::
- Feasibility of Project ::
- Style & Grammar  ::
- *Grade* :: ") (FinalProject:BookExhibit :courseid "127426" :canvasid "233045" :due-at "2019-11-29" :html_url "https://q.utoronto.ca/courses/127426/assignments/233045" :name "Final Project: Book Exhibit" :submission_type "online_upload" :published "t" :submission_url "https://q.utoronto.ca/courses/127426/assignments/233045/submissions?zip=1" :basecommit "none" :org_lms_email_comments nil :org_lms_canvas_comments nil :grade_type "letter_grade" :assignment-type "canvas" :directory "final-project:-book-exhibit" :rubric "- *Grade* ::
- Comments :: "))