#+MACRO: ts (eval(mwp-get-ts+7  'org-mwp-classtimes-calibrate 2))
#+STARTUP: customtime
#+ORG_LMS_COURSEID: 99251
#+STARTUP: customtime
#+HUGO_BASE_DIR: ./website/
#+HUGO_SECTION: assignment
#+HUGO_STATIC_IMAGES: Images
#+HUGO_MENU: :menu main :parent Assignments
#+HUGO_AUTO_SET_LASTMOD: t

* COMMENT Hugo Instructions
- Every exportable entry must have the ~EXPORT_FILE_NAME~ property set before export.


** Check out this elisp code if you're having trouble

#+begin_src emacs-lisp
(use-package ox-hugo-auto-export)

#+end_src

#+RESULTS:

* Overview
:PROPERTIES:
:EXPORT_FILE_NAME: overview
:END:

testing out the overview
 



* Participation


* Reflection 01: DH Project Profile
:PROPERTIES:
:EXPORT_FILE_NAME: reflection-1-project-profile
:PUBLISH:  t
:DUE_AT: 2019-05-13
:GRADING_TYPE: letter_grade
:ASSIGNMENT_TYPE: canvas
:ASSIGNMENT_WEIGHT: 0.15
:CANVAS_SUBMISSION_TYPES: (online_upload)
:OL_PUBLISH: t
:BASECOMMIT: none
:CANVASID: 168376
:CANVAS_HTML_URL: https://q.utoronto.ca/courses/99251/assignments/168376
:CANVAS_SUBMISSION_URL: https://q.utoronto.ca/courses/99251/assignments/168376/submissions?zip=1
:SUBMISSIONS_DOWNLOAD_URL: https://q.utoronto.ca/courses/99251/assignments/168376/submissions?zip=1
:GRADING_STANDARD_ID: nil
:END:

Your first assignment is to profile a Digital Humanities project, analyzing its research aims, its form and content, its interface, technologies, and intended audience. You will learn how to navigate Digital Humanities projects, how to identify and evaluate different aspects of such projects, and how to analyze the kinds of knowledge and digital artifacts generated by DH projects. *Write-up: 500 words plus screenshots*.

You may select any project you like from the syllabus or from one of the pages below:

- [[https://digitalhumanities.duke.edu/all-projects]] (please start here)
- [[https://eadh.org/projects]] (override security warning to view; expired certificate does not preally pose a risk here)
- https://cdh.unc.edu/prsp-template/proj_init/
- [[https://dhcommons.org/projects]] (Oops! Down right now!)

This project profile is not an essay; it is a short, 1-2 page report. You do not need to write a formal introduction, thesis, argument, or conclusion. You should only report on your observations, using the questions below as categories of analysis, each with its own heading. Not all categories and questions apply to all projects, so *do not feel obligated to respond to all of them*. Your project profile will be evaluated for [[http://www.artsci.utoronto.ca/newstudents/transition/academic/grading][accuracy, clarity, detail, quality of analysis, and insight]].


1. *Project:* What is the name of the project? Who are its primary authors?

2. *Topic:* What is the project about? (Examples: What topic and historical period does it focus on? What texts or art works or other material does it collect, explain, map, or analyze? What questions is the project seeking to answer?)

3. *People & Institutions*: Who is the project leader? Who are their collaborators? What is the institution involved in the project's development? What are the granting bodies funding the projects? Is credit given to individual contributors? To what extent?

4. *Presentation & User Experience:* What is the “digital artifact” through which this project communicates its findings? A book? A game? A map? An edition? An archive? A tool? Another type of digital artifact?

   As a user external to the project, what steps did you take to explore the project? Can you understand how to read the project's data or how to use the tools it is building? As you explore the project, what do you find easy? What do you find difficult? What do you like? What do you dislike? Document your experience with screenshots, please ([[https://screenshots.firefox.com/][firefox's screenshot tool]] makes this very easy).

   Does this project provide access to users with e.g. limited bandwidth, minimal computing (e.g. smartphones instead of laptops), vision or hearing or tactile impairment?

5. *Data:*  What data does the project generate? What data format(s): text files, pdf files, digital images, databases, Excel or .csv files? Does the project provide narrative context for its data (that is, does it clearly explain what its data means and why it matters, for readers not familiar with the project)? Is access to project data open, subscription-only, or under a specific licence? May other scholars download the project's data?

6. *Technologies:* What technologies (encoding formats, digital publication platforms, software) are used in this project or built as part of this project? Are these technologies open-source, open-access?

7. *Audience:* Who is the intended audience for this project? That is, does this project primarily speak to laypeople? Scholars? Specialists? How can you tell?

8. *Limitations:* Does the project make note of any limitations in its work, any gaps or uncertainties in its data? Can you find limitations in its work---that is, gaps between its stated goals and its results?

This assignment is based on the [[https://dmptool.org/][DMP Tool]], the U of T DH Census Profile tool, and [[https://docs.google.com/document/d/1jp0bQ18hXKxekgACfBCw_6P6lO_xg4uzUXXMvT2jaPo/edit][Kristen Mapes]]' DH Project Critique assignment.

* Reflection 02: 

* Reflection 03: Data visualization Comparison
:PROPERTIES:
:EXPORT_FILE_NAME: reflection-3-data-visualization
:PUBLISH:  t
:DUE_AT: 2019-06-03
:GRADING_TYPE: letter_grade
:ASSIGNMENT_TYPE: canvas
:ASSIGNMENT_WEIGHT: 0.15
:CANVAS_SUBMISSION_TYPES: (online_upload)
:OL_PUBLISH: t
:BASECOMMIT: none
:GRADING_STANDARD_ID: nil
:CANVASID: 169214
:CANVAS_HTML_URL: https://q.utoronto.ca/courses/99251/assignments/169214
:CANVAS_SUBMISSION_URL: https://q.utoronto.ca/courses/99251/assignments/169214/submissions?zip=1
:SUBMISSIONS_DOWNLOAD_URL: https://q.utoronto.ca/courses/99251/assignments/169214/submissions?zip=1
:END:

*Please download the template document, which can be found in the files section of Quercus, which will make it easier to fill in the form.  If you prefer to write in another format, (such as markdown) that is fine too.*


Using the following table, compare and contrast two of the data visualization tools we have used in this course: Tableau, Voyant, Palladio. Think about the Drucker, Nowviskie, and Posner readings, especially with respect to the Assumptions category!

| /Tool/Platform/                                 |   |   |
|-------------------------------------------------+---+---|
| *Brief Description*                             |   |   |
| *Data: nature, format, & other characteristics* |   |   |
| *Output*                                        |   |   |
| *User Experience*                               |   |   |
| *User Base*                                     |   |   |
| *Use Cases*                                     |   |   |
| *Assumptions about Knowledge (Input, Output)*   |   |   |


* Paper Assignment 1
* COMMENT Local Variables                          
# Local Variables:
# org-hugo-auto-export-on-save: t
# End:
