#+MACRO: ts (eval(mwp-get-ts+7  'org-mwp-classtimes-calibrate 1))
#+TITLE: WDW235 Syllabus
#+ODT_STYLES_FILE: "/home/matt/.emacs.d/Templates/syl-temp-2019.odt"
#+STARTUP: customtime
#+ORG_LMS_COURSEID: 99251
#+HUGO_BASE_DIR: ./website/
#+HUGO_SECTION: syllabus
#+EXPORT_FILE_NAME: syllabus
#+HUGO_STATIC_IMAGES: images
#+HUGO_MENU: :menu main :weight 10
#+HUGO_CUSTOM_FRONT_MATTER: :banner "testbanner"
# #+IS_PUBLIC: t

* Course Details
   :PROPERTIES:
   :CUSTOM_ID: course-details
   :END:

| Instructor   | Matt Price                                            |
| Course Hours | Th 5-8                                            |
| Office Hours | Th 1-2  (SS 3077)                         |
| Email        | [[mailto:alexandra.bolintineanu@utoronto.ca][matt.price@utoronto.ca]] (weekdays 9-5, 48h turnaround) |

* Course Description
   :PROPERTIES:
   :CUSTOM_ID: course-description
   :END:

Digital Humanities (DH) is a discipline at the intersections of the humanities with computing.  DH studies human culture -- art, literature, history, geography, religion -- through computational tools and methodologies; and, in turn, DH studies digital artifacts through humanist lenses, as complex cultural objects shaped by wider social, political, and philosophical concerns. Digital humanists [[http://www.doe.utoronto.ca][analyze languages through digital text collections]]; [[https://samizdat.library.utoronto.ca/][build digital archives of forbidden books]]; [[http://sites.utm.utoronto.ca/gillespie/content/welcome-book-fame][construct video games to study literature]]; or [[https://decima-map.net/][resurrect historical cities through digital maps]].

This year, the course once again focuses on endangered books: /fragile, hidden, censored, forbidden/. We speak to scholars who build archives of forbidden literature. We visit the Thomas Fisher Rare Book Library. We study rare books' histories through digital exhibits. By the end of the course, you will have mastered concepts and technologies you can use in future courses and workplaces:  text encoding and data visualization, data analysis and digital exhibit platforms. And you will learn how our stories and cultural conversations work and shapeshift through digital environments.

* Learning Goals
   :PROPERTIES:
   :CUSTOM_ID: learning-goals
   :END:

By the end of the course:

- You will be able to describe the history and intellectual landscape of the digital humanities, including the central concepts, debates, projects, and digital tools current in the discipline.
- You will have developed a set of best practices around datasets, project design and management, and data curation.
- You will have analyzed data and digital artifacts as complex cultural objects, shaped by, and shaping, how we live, think, and know.

Through hands-on workshops:

- You will experiment with text encoding, quantitative text analysis, and text-based videogames as tools of scholarly research
- You will create and analyze data visualizations
- You will research and author your own digital exhibit

* Course Readings & Technologies
   :PROPERTIES:
   :CUSTOM_ID: course-readings-technologies
   :END:

Course readings will be available either as links in the syllabus or via the course Quercus site each week. You are responsible for checking the Quercus site and ensuring you receive course announcements posted via Quercus.

All technologies used in this course are open-source or, in rare cases, licensed for use by U of T students. You will need access to a working computer to complete the work for this course.

* How This Course Works
   :PROPERTIES:
   :CUSTOM_ID: how-this-course-works
   :END:

Each week we have three hours of class, which include lecture, discussion, and hands-on work in the computer lab. Much of your course work will be done in class, in facilitated environments and hands-on workshops. Given the fast pace and praxis-oriented environment, you must come to class on time, all the time: it is all too easy, otherwise, to get lost. If this poses a problem, please let me know as soon as possible.

* Accessibility 
   :PROPERTIES:
   :CUSTOM_ID: accessibility-www.studentlife.utoronto.caas
   :END:

Students with diverse learning styles and needs are more than welcome in this course. Please feel free to approach me or Accessibility Services so we can assist you in achieving academic success in this course. 

See [[http://www.studentlife.utoronto.ca/as][A&S Accessibility Website]] for more details on the Accessibility policy.

* Grading Scheme
   :PROPERTIES:
   :CUSTOM_ID: grading-scheme
   :END:

| *Assignment*                                    | *%* | *Due Date*                                    |
|-------------------------------------------------+-----+-----------------------------------------------|
| Short Assignments (3)                           |  45 | <2019-09-19 Thu>, <2019-10-10 Thu>, <2019-11-21 Thu>               |
| Participation                                   |  10 | All semester; alternatives.                   |
| Book Project: Consultation                      |   1 | Oct. 11-25, in office hours or by appointment |
| Book Project: Proposal & Annotated Bibliography |   9 | <2019-11-01 Fri>                                     |
| Book Project: Digital Exhibit                   |  35 | <2019-11-29 Fri>                                     |
| Total                                           | 100 |                                               |
#+TBLFM: @>$2=vsum(@2..@-1)

- Reflections include in-class digital artifacts as well as discussion of course readings.
- You will work on reflections in class as well as outside class, and you will hand them in via Quercus. 400-500 words maximum.

* Graded Work
   :PROPERTIES:
   :CUSTOM_ID: assignments
   :END:
** Participation
Every week, you are also responsible for coming to the lab and undertaking the project or field trip of the week in a facilitated environment.  This is where you can explore, experiment, fail creatively:  all I require is *engaged participation—that is, you come to class, do the hands-on computer work, ask questions, and engage in class discussion*. If you miss class or are more than ten minutes late for class, you will miss the grades, unless your absence is excused. 
** ACTION Reflection Portfolio

You are responsible for writing three reflections in this course. Reflections include in-class digital artifacts as well as discussion of course readings. You will work on reflections in class as well as outside class, and you will hand them in via Quercus. They need not be perfect, just done. 400-500 words maximum.

** DH Project Profile

Your first assignment is to profile a Digital Humanities project, analyzing its research aims, its form and content, its interface, technologies, and intended audience. 500-700 words. You will select the project from a sign-up list available via our course site.

** Book Project

Your major assignment in this course is to tell the story of a banned, challenged, or endangered book through a digital exhibit.

* Contact
   :PROPERTIES:
   :CUSTOM_ID: contact
   :END:

I love hearing from you! *The best way to contact me is to talk to me in person in office hours.* I also answer emails at [[mailto:matt.price@utoronto.ca][matt.price@utoronto.ca]] within 48 hours or fewer on business days. However, I do not answer email after 5:00 p.m. or on weekends, and I do not expect you to do so, either. Please email me as soon as possible to make sure you receive your answers in good time.

* Due Dates & Late Penalties
   :PROPERTIES:
   :CUSTOM_ID: due-dates-late-penalties
   :END:

- Assignments :: Assignments are due at the beginning of each class. Late assignments will be penalized three percentage points per day unless you have prior permission from the instructor in writing (email). (Of course, late penalties do not apply when the lateness was caused by illness, bereavement, or other serious circumstances outside students' control. For religious observances, please notify instructor before the due date.)

- Lab Work :: If you miss a class, you are responsible for catching up with the work and will not receive credit for that class. (Of course, I will not penalize you if your absence is caused by illness, bereavement, religious observances, or other serious circumstances outside students' control.)

- Documentation needed for extensions :: As a matter of fairness to all students, you may be required to support any request for extensions or makeup test with supporting documentation. For medical issues, documentation consists of UofT's [[http://www.illnessverification.utoronto.ca/getattachment/index/Verification-of-Illness-or-Injury-form-Jan-22-2013.pdf.aspx][Verification of Student Illness or Injury form]]. For non-medical issues, documentation consists of a note from the student's College Registrar, social worker, clergy etc. Non-medical notes must contain the same information requested on U of T's [[http://www.illnessverification.utoronto.ca/getattachment/index/Verification-of-Illness-or-Injury-form-Jan-22-2013.pdf.aspx][Verification of Student Illness or Injury form]].

- Re-marking :: The deadline for requesting a re-marking is one week from the date the term work was made available for pickup. Unfortunately, I am unable to accept late re-marking requests.

* Academic Integrity
   :PROPERTIES:
   :CUSTOM_ID: academic-integrity
   :END:

In this course, you will work with texts, objects, and digital artifacts. As you navigate the world of digital cultural heritage and write for a wider public, you are allowed (indeed, encouraged!) to use the work of others -- but you must carefully and conscientiously acknowledge your sources, give credit where credit is due, and respect [[http://www.artsci.utoronto.ca/osai/The-rules/what-is-academic-misconduc][the University of Toronto's expectations of academic integrity]].

* Acknowledgments
   :PROPERTIES:
   :CUSTOM_ID: acknowledgements
   :END:

This syllabus was originally written by [[https://alexandrabolintineanu.wordpress.com/][Alexandra Bolintineanu]], and draws on both Kristen Mapes' /[[http://dx.doi.org/10.17613/M6H34B][Introduction to Digital Humanities, AL285]]/ and on Miriam Posner's /[[http://dh101.humanities.ucla.edu/][DH101: Introduction to Digital Humanities]]/ Fall 2014, UCLA.

* Course Overview (Subject to Change)
   :PROPERTIES:
   :CUSTOM_ID: course-overview
   :END:
** {{{n}}} ({{{ts}}}) Introduction to Digital Humanities
What is “Digital Humanities”? We discuss the range of projects, activities, and concerns of this growing field, and collaboratively survey representative projects from around the world. We discuss DH in relation to the theme of the course, banned books. 

*** Tool Workshop: [[https://twinery.org/][Twine]]
- How do digital media change possibilities for humanists to express themselves and craft persuasive arguments? We experiment via a popular game-design tool.
** {{{n}}} ({{{ts}}}) The Anatomy of DH Projects
We discuss the components of digital humanities projects—data, code, tools, platforms, standards and communities of practice—as they manifest across a gallery of projects, living or dead. We investigate success, failure, and sustainability in DH projects. We collaboratively analyze two DH projects, peering “under the hood” of their technical framework and examining their research questions, digital artifacts, user experiences and intended audiences, and disciplinary implications.

*** Readings and Discussion: 
- Miriam Posner, “[[http://miriamposner.com/blog/how-did-they-make-that/][How Did They Make That?]]” (2013) 
- Alan Galey & Stan Ruecker, “[[https://doi.org/10.1093/llc/fqq021][How a Prototype Argues]]” (2010) (in-class discussion)
*** Reflection Handed Out: DH Project Profile
*Due May 13*
** {{{n}}} ({{{ts}}}) Endangered Knowledge 1: Rare Books & Digital Archives

The first part of class is devoted to understanding the main course assignment, with some lecture material about *endangered knowledge*

*** Tools Workshop: Omeka
A *very* brief intro to Omeka, the framework we'll use to build your class projects.

*** Class Outing: Banned and Censored Books
We visit the Thomas Fisher Rare Book Library under the guidance of Tim Stinson, Cataloguer and Reference Librarian at the Library, and are introduced to the candidate books for your final projects.

*Please Note:* due to an unfortunate scheduling difficulty, our only window for this visit is 12:00-1:30 today. I am hopeful that everyone in the class can stay for this entire period. 
** {{{n}}} ({{{ts}}}) Digital Texts: Reading and Writing
*Endangered ‘book’: oral poetry, cultural memory*
- Kinds of danger, types of responses
- Using digital methods to discover and highlight new understanding of literary texts
*** Readings & Discussion: 	 
:PROPERTIES:
:ID:       9e3b927f-9757-4dc2-83bd-3d312f10cd10
:END:
- Lisa Samuels and Jerome J. McGann, “[[http://bf4dv7zn3u.search.serialssolutions.com.myaccess.library.utoronto.ca/?ctx_ver=Z39.88-2004&ctx_enc=info%253Aofi%252Fenc%253AUTF-8&rfr_id=info%253Asid%252Fsummon.serialssolutions.com&rft_val_fmt=info%253Aofi%252Ffmt%253Akev%253Amtx%253Ajournal&rft.genre=article&rft.atitle=Deformance+and+Interpretation&rft.jtitle=New+Literary+History%253A+a+journal+of+theory+and+interpretation&rft.au=Samuels%252C+Lisa&rft.au=McGann%252C+Jerome&rft.date=1999&rft.issn=0028-6087&rft.eissn=1080-661X&rft.volume=30&rft.issue=1&rft.spage=25&rft.externalDocID=R03182533][Deformance and Interpretation]],” /New Literary History/ 30, No. 1 (Winter, 1999): 25-56. (in-class discussion) 	 
- Alan Liu, “[[http://www.digitalhumanities.org/companion/view?docId=blackwell/9781405148641/9781405148641.xml&chunk.id=ss1-3-1&toc.depth=1&toc.id=ss1-3-1&brand=9781405148641_brand][Imagining the New Media Encounter]].” A Companion to Digital Literary Studies. Ed. Ray Siemens and Susan Schreibman. Malden, MA: Blackwell, 2007. 3-25
*** Tool Workshop/Reflection Assignment: [[https://tei-c.org/][TEI]] and The Ruin
- How do digital humanities text analysis tools open new ways of reading literature? We experiment with text encoding using 
*Reflection 2 Due May 22*
** {{{n}}} ({{{ts}}}) NO CLASS VICTORIA DAY
** {{{n}}} ({{{ts}}}) Data: OpenRefine
- A special 3-hour workshop with OpenRefine in the Map and Data Library (5th Floor Robarts)

*** Data & Map Workshop with Kelly Schultz
Introduction to data cleaning with [[http://openrefine.org/][OpenRefine]], a powerful data cleaning and transformation tool. 
** {{{n}}} ({{{ts}}}) UNSUPERVISED WORK SESSION!
I'll be away! You are free to use the classroom, though, to make progress on your work. We'll discuss this more as the date gets closer.  
** {{{n}}} ({{{ts}}}) Data 2: Data Models for the Humanities
We back up and ask: what are data models and algorithms? We discuss how data models, algorithms, and digital platforms inform ways of knowing, learning, and reading. Data as endangered/endangering knowledge. 

*** Readings & Discussion:
- Miriam Posner, [[http://miriamposner.com/blog/humanities-data-a-necessary-contradiction/][Humanities Data: A Necessary Contradiction]] (2015) Accessed April 30, 2019. 
- Rob Kitchin, “Conceptualising Data.”  /[[http://methods.sagepub.com.myaccess.library.utoronto.ca/book/the-data-revolution][The Data Revolution:  Big Data, Open Data, Data Infrastructures & Their Consequences]]/ (2014) 
*** Further Reading:
- U of T's [[https://onesearch.library.utoronto.ca/researchdata][research data management policies]], including [[https://onesearch.library.utoronto.ca/researchdata/sensitive-data][guidelines on handling sensitive data]] (including de-identification, i.e. anonymizing your data) and on [[https://onesearch.library.utoronto.ca/researchdata/funder-requirements][Canadian funders' data publication requirements]] (two of the three federal funding bodies mandate that data created with gov't funding be made public).
- Cathy O’Neil, /[[https://search.library.utoronto.ca/search?Ntx=mode%2520matchallpartial&Ntk=Anywhere&N=0&Ntt=%2522weapons%2520of%2520math%2520destruction%2522&Nr=p_work_normalized:ONeil%2520Cathy%2520Weapons%2520of%2520math%2520destruction&uuid=7c23a669-7240-41dc-94d6-592f201cb609][Weapons of Math Destruction: How Big Data Increases Inequality and Threatens Democracy]]/. (2016)
- Safiya Umoja Noble. /[[https://ebookcentral-proquest-com.myaccess.library.utoronto.ca/lib/utoronto/detail.action?docID=4834260][Algorithms Of Oppression: How Search Engines Reinforce Racism]]/. (2018)
*** Reflection Assignment: Data Tool Comparison
*Reflection Due June 03*

** {{{n}}} ({{{ts}}}) Endangered Knowledge 2: Theory and Practice
We examine digital archives, discussing creation, preservation, ethical concerns, relationships with communities, and security and environmental issues raised by cloud computing and machine learning.  We examine UofT’s guidelines around the ethical and technical management of human research data.
*** Readings & Discussion
On Resurrections, Risks, Losses
William Noel, “[[http://www.ted.com/talks/william_noel_revealing_the_lost_codex_of_archimedes][Revealing the Lost Codex of Archimedes]]” (2012). [TED TALK]
Bethany Nowviskie, “[[http://nowviskie.org/2014/anthropocene/][Digital Humanities in the Anthropocene]]”
Eira Tansey, “[[http://eiratansey.com/2017/05/16/fierce-urgencies-2017/][When the Unbearable Becomes Inevitable: Archives and Climate Change]]” (2017).

*** Tools Workshop: More Omeka 
** {{{n}}} ({{{ts}}}) Endangered Knowledge 3: Remembering the Soviet Bloc
*** Readings & Discussion
- Browse *extensively* in the [[https://samizdatcollections.library.utoronto.ca/][Project for the Study of Dissidence and Samizdat]]
*** Special Guest Lecture!
[[https://alexandrabolintineanu.wordpress.com/][Prof. Alexandra Bolintineanu]] will share some reflections on Samizdat and censorship in late Twentieth Century Romania.  
** {{{n}}} ({{{ts}}}) Data Visualization
In facilitated workshops, we turn to data visualization of humanities materials, using Jane Austen’s /Lady Susan/ for experimentation ([[https://voyant-tools.org/][Voyant]], [[http://hdlab.stanford.edu/palladio/][Palladio]], [[https://cytoscape.org/][Cytoscape]], [[https://www.tableau.com/][Tableau]]:  text and corpus work, network graphs, mapping, annotation).  Then we analyze the American Library Association’s data on banned books and discuss how we might model, interpret, question, and visualize this data.

*** Readings & Discussion
- Johanna Drucker, “[[http://www.digitalhumanities.org/dhq/vol/5/1/000091/000091.html][Humanities Approaches to Graphical Display]]” /Digital Humanities Quarterly/ (2011).
- Miriam Posner, [[https://www.youtube.com/watch?v=sW0u1pNQNxc][Data Trouble: Why Humanists Have Problems with Datavis, and Why Anyone Should Care]] (2016) 

** {{{n}}} ({{{ts}}}) DV 2
Continuation of previous Session
** {{{n}}} ({{{ts}}}) Retrospective
The last class is a retrospective look at the course. We'll discuss how to use DH approaches and tools in your home disciplines. We also discuss how we might apply the course learning outcomes to jobs in the corporate sector: we dissect a job ad from Monster.ca to align students' newly acquired skills with every requirement of that position.


   
* COMMENT Variables
#+begin_src emacs-lisp
(make-local-variable 'org-use-property-inheritance)
(setq org-use-property-inheritance nil)
(setq org-lms-baseurl "https://q.utoronto.ca/api/v1/")
(setq org-lms-token (password-store-get "q.utoronto.ca"))
;;(org-lms-set-keyword "ORG_LMS_COURSEID" 64706)

(org-lms-setup)
#+end_src
local variables need to be set at the end of the file.  
# Local Variables:
# org-time-stamp-custom-formats: ("<%b. %d>" . "<%Y-%m-%d %H:%M>")
# org-mwp-classtimes-calibrate: ("<2019-05-01 Thu>" "<2019-04-29 Tue>" )
# End:  
