* A Book's Tale: Building a Digital Exhibit
  :PROPERTIES:
  :CUSTOM_ID: a-books-tale-building-a-digital-exhibit
  :END:

** Overview
   :PROPERTIES:
   :CUSTOM_ID: overview
   :END:

In this assignment, you get to tell the story of a banned book you have seen in person, either from the Thomas Fisher Rare Book Library or from our list.

You will create a website that features a digital collection and exhibit about that book, using the free, open-source content management platform Omeka. Like a good museum curator, you will bring together a gallery of exciting pictures, and you will guide your visitors through that gallery through a well-researched, interesting narrative about your book.

- Your digital collection will catalogue evidence about your book: photographs of the book itself (title page, illustrations, marginal annotations, damage, other interesting features); images of related books from other museums; manuscript illuminations; other relevant multimedia. Each object of your digital collection will be described systematically, as books are described in a library catalogue.

- Your exhibit will be a guided tour about your book and the circumstances under which it was banned.

- You will use some digital technology as part of this assignment.

This is a scaffolded assignment: that is, you will produce several components at each stage, and each component builds on the ones before it-- like LEGO, except you get to build your own bricks.

** Learning Goals
   :PROPERTIES:
   :CUSTOM_ID: learning-goals
   :END:

By the end of this learning module, you will have learned:

- How to understand your book's significance, history, and meaning, in its historical context;

- How to think about the transmission and attempted restriction of knowledge in different technological platforms (manuscripts, printed books, digital media)

- How to build an exhibit around objects and their history;

- What metadata is, and why metadata matters

- What Omeka is, and what content management systems are
  
- How to create your own Omeka site: building items, creating digital collections and building exhibits featuring scholarly materials
  
** What You Hand In:
   :PROPERTIES:
   :CUSTOM_ID: what-you-hand-in
   :END:

1. A proposal describing, in 200 words or fewer, the object whose story you plan to tell: what it is; why it was banned, by whom, and in what historical context; and how you plan to shape your exhibit. *Due <2019-06-05 Wed>*

2. An annotated bibliography ([[http://advice.writing.utoronto.ca/types-of-writing/annotated-bibliography/]]) that contains: links to and descriptions of at least 3 things for your collection; references to and summaries of at least 3 *scholarly* sources (scholarly print books, scholarly journal articles, scholarly encyclopedia entries). *Due <2019-06-17 Mon>*

3. A complete digital exhibit website that contains your collection of objects and a narrative about that collection. For reference, a former student's UofT Library Research Prize-winning example of such a digital exhibit is d:escribed in detail here [[https://tspace.library.utoronto.ca/handle/1807/88308][Jaya Thirugnanasampanthan's exhibit on /Thirteen Reasons Why/'s banning in the U.S.]] (you will have to click through a bit to find [[https://play.library.utoronto.ca/download/XPYcIMVV80N4][a link to a walkthrough of the site]]).

** Proposal
   :PROPERTIES:
   :CUSTOM_ID: proposal
   :END:

*100-200 words*: describe your book and the structure of your exhibit.

*Sample Proposal*

+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+
| *Example*                                                             | *Discussion*                                                                                  |
+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+
| My exhibit focuses on Ana Blandiana's /Întâmplări de pe strada mea/   | One sentence identifying your object and its place/time of origin.                            |
|(‘Events From My Street'), a Romanian children's book, which was banned|                                                                                               |
|in Romania during the Ceaușescu regime.                                |                                                                                               |
|                                                                       |                                                                                               |
+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+
| I will discuss this book from the following points of view:           | An overview of your exhibit: its sections and some of its objects.                            |
|                                                                       |                                                                                               |
|                                                                       |                                                                                               |
+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+
|                                                                       |                                                                                               |
+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+
| *Book*. I describe the book itself, an illustrated children's book in | You will probably have less to say in your proposal: that is FINE. Indicate who banned the    |
|verse.                                                                 |book, and why, and how your exhibit will                                                       |
|                                                                       |                 show this.                                                                    |
|                                                                       |                                                                                               |
|                                                                       |                                                                                               |
|                                                                       |                                                                                               |
+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+
|                                                                       |                                                                                               |
+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+
|*Ban or Challenge*. I discuss why the book was scrutinized by the      |                                                                                               |
|Communist regime. Some items here include: photos of the pages with the|                                                                                               |
|poem “A star on my street,” a poem about a boastful kitten which was   |                                                                                               |
|interpreted as a criticism of the dictator Ceausescu and caused the    |                                                                                               |
|book to be scrutinized by the Securitate (the secret police); archival |                                                                                               |
|photos of schoolchildren forced to celebrate Ceausescu; and children's |                                                                                               |
|textbooks featuring first-page photographs of Ceausescu. These         |                                                                                               |
|artifacts show how official culture sought to frame and control the    |                                                                                               |
|experience and knowledge of childhood.                                 |                                                                                               |
|                                                                       |                                                                                               |
| *Conclusion.* I discuss children's literature in Communist Romania as |                                                                                               |
|a space in which writers dared to experiment, because children's books |                                                                                               |
|allowed writers to say uncomfortable things in playful or disguised    |                                                                                               |
|ways.                                                                  |                                                                                               |
|                                                                       |                                                                                               |
|                                                                       |                                                                                               |
| I contrast this with the ways the contemporary school system, in their|                                                                                               |
|censorship of e.g. history books, competed to shape children's worlds  |                                                                                               |
|and knowledge, selecting the literature and history curriculum to      |                                                                                               |
|reflect the ideology of the totalitarian government.                   |                                                                                               |
|                                                                       |                                                                                               |
+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+

** Collection
   :PROPERTIES:
   :CUSTOM_ID: collection
   :END:

*5 Items or more, to be described with Dublin Core metadata, including photos of your book:*

The collection is a set of at least 5 items that document your book and the context in which it was banned. Photographs of the book should be taken by yourself; the other photographs, you may find on museum websites and cite properly.

Some examples of objects that shed light on your book and the context in which your book was banned:

- If you are studying a book banned in Nazi Germany, find digitized archival photographs documenting e.g. book burnings in Nazi Germany;

- If you are studying a book banned by the Catholic Church, photograph the Index;

- If you are studying, say, Darwin's /Origin of Species/, you can document its impact with photos of 19^{th} century newspaper articles about it...or with 21^{st} century newspaper articles on the controversy around the depiction and teaching of evolution vs. creationism in U.S. schools

- If you are studying a science book, you can illustrate the science of the day with museum pictures of relevant scientific instruments (microscopes, telescopes);

- If you are studying a book of saints' lives (banned by Protestants) or a theological work (attacking the Catholic Church), you may look for contemporary images of e.g. book burnings, anti-Papal posters, etc.

** Exhibit
   :PROPERTIES:
   :CUSTOM_ID: exhibit
   :END:

In every exhibit, at least four sections are mandatory: */Introduction/*; */Book/*; */Context/*; and */Insights/*. You may include other sections if needed.

*** Introduction

This section is a summary of your exhibit, indicating what your book is, when it was banned, and why. 100-150 words. (A cleaned-up version of your proposal.)

*** Book

In this section, you describe your book and its author. What is its title? Who is its author? In detail and in your own words, summarize what the book is about. [size; shape; damage; marginal annotations, if any; illustrations, if any; other distinguishing marks, if any.) Your items in this section can be different photos of your book. Include as much descriptive detail as you can.

*** Context

In this section, you describe the social and historical context of your book: that is, the book's *time*, *place*, and *purpose*. When and where was it written? What text technologies were involved in its creation? To what effect? Who was its intended audience? Why is the book in danger? If it is a banned or censored book, then who banned or challenged the book, and why? How was this censorship or challenge enforced? Your exhibit items can include maps, photographs of people reading the book, photographs of people destroying the book, recordings, etc.

*** Insights

What insights (specific to your book---not a general conclusion that almost any other banned or endangered book could illustrate) into text technologies and the transmission of knowledge would you like your viewer to draw from your exhibit?

More specifically: how do the cultural and technical conditions in which the book was produced affect its endangerment and its afterlife? And how does the digital exhibit help you reflect on the text culture of your book?

Draw on the scholarly readings of this course, from Alan Liu to Bethany Nowviskie, to discuss the “new media encounter” moment between the endangered book and your presentation of it in a digital medium. (Some things to think about: textual stability, deformance, sustainability, new media encounters, deep time...)

*** Works Cited

This section contains resources---scholarly articles or museum articles or books---on which your exhibit draws. You may use any scholarly citation style you like, as long as you are consistent.

Example:

Gogâță, Cristina. “Parallel Libraries Of The Former Securitate. Ana Blandiana, ‘Întâmplări De Pe Strada Mea' (‘Events From My Street').” Studia Universitatis Babes-Bolyai. 61(2): 2006, pp. 97-100.

/Happy researching!/

** Books
   :PROPERTIES:
   :CUSTOM_ID: books
   :END:

You will select the book from the list below. If there is a book you would like to cover that is not on the list, please come talk to me *well ahead* of the proposal deadline. No more than three students per book, please.

Books from the Thomas Fisher Rare Book Library (use these specific editions, please):

1. Martin Luther. /Piae ac doctae in psalmos operationes/. Basileae: Adamus Petri, 1521.

2. Judah ben Samuel. /Sefer ha hasidim/. Bolonya: Avraham ha-Kohen b.k.mo.ha-r. Mosheh ha-Kohen, 5298 (1537/1538 CE).

3. Nicholas Copernicus. /De revolutionibus orbium coelestium./ Basileae: Ex Officina Henricpetrina, 1566.

4. Johannes Kepler. /Epitome astronomiae Copernicanae/. Lentijs ad Danubium: Excudebat J. Plancus, 1618-22.

5. /The Holy Bible: Containing the Old and New Testaments./ London: Robert Barker, 1631.

6. Galileo Galilei. /Dialogo sopra I due massimi sistemi del mondo tolemaico e copernicano./ In Fiorenza: B. Landini, 1632.

7. Albertus Magnus. /De secretis mulierum. Item de virtutibus herbarum, lapidum et animalium./ (Of the secrets of women. Also about the virtues of herbs, stones, and animals. [magic])

8. Charles Darwin. /On the Origin of Species/. London: J. Murray, 1859.

9. Sigmund Freud. /Vorlesungen zur Einführung in die Psychoanalyse/. Leipzig und Wien: H. Heller, 1916-1917.

10. Niccolo Machiavelli. /Princeps/. Basiliae, 1589.

11. Rene Descartes. /Les méditations métaphysiques./ Paris: La veuue I. Camvsat, et P. le Petit, 1647.

12. John Milton. /Pro populo Anglicano defensio/. Londini: Typis Du Gardianis, 1651.

13. John Locke. Essay Concerning Human Understanding. London: Printed by Eliz. Holt, for Thomas Basset, 1690.

14. David Hume. /Philosophical Essays Concerning Human Understanding./ London: Printed for A. Millar, 1749.

15. John Wilkes. /The North Briton/, No. XLV. London, 23 April 1763.

16. Voltaire. /Dictionnaire philosophique./ 1765.

17. Thomas Paine. /The Rights of Man./ London: Printed for J.S. Jordan, 1791-2.

18. Karl Marx and Friedrich Engels. /The Manifesto of the Communist Party/. Vancouver: Whitehead Estate, 1919.

19. Dante Alighieri. /La commedia./ Vinegia: Petrus de Plasiis, Cremonensis, dictus Veronensis/,/ 18 Nov., 1491.

20. Geoffrey Chaucer. /The Canterbury Tales./ London: Printed by [R. Grafton for] Wyllyam Bonham, 1542.

21. Giovanni Boccaccio. /Il Decameron./ In Vinezia: Per li Giunti di Frienze, 1585.

22. Nathaniel Hawthorne. /The Scarlet Letter./ Boston: Ticknor, Reed, and Fields, 1850.

23. Walt Whitman. /Leaves of Grass/. Brooklyn, 1856.

24. George Eliot. /Adam Bede/. Edinburgh: W. Blackwood, 1859.

25. Victor Hugo. /Les miserables/. Bruxelles: A. Lacroix, Verboeckhoven, 1862.

26. Mark Twain. /Adventures of Tom Sawyer./ Toronto: Belford Bros., 1876.

27. Aristophanes. /Lysistrata/. Sydney: Fanfrolico Press, 1925.

*** Useful Resources

/Reference Works:/

- American Library Association. [[http://www.ala.org/advocacy/bbooks][Banned & Challenged Books.]]

- Carefoote, Pearce J, and Alberto Manguel. /Nihil Obstat: An Exhibition of Banned, Censored & Challenged Books in the West, 1491-2000; Exhibition and Catalogue/. Toronto: University of Toronto Library, 2005. Print.

- /Censorship: 500 Years of Conflict/. New York, N.Y: Oxford University Press, 1984. Print.
- [[http://www.oxfordbibliographies.com.myaccess.library.utoronto.ca/view/document/obo-9780199791286/obo-9780199791286-0015.xml][Censorship]] (Oxford Bibliographies Online).

/Book & Image Repositories:/

- [[https://www.bl.uk/victorian-britain][British Library]]

- [[http://www.britishmuseum.org/research/collection_online.aspx][British Mueum]]

- [[https://dp.la/][Digital Public Library of America]]

- [[http://digital.bodleian.ox.ac.uk/][Digital Bodleian]]

- [[http://art.thewalters.org/browse/category/manuscript-and-rare-books/][Walters Art Museum]]

- [[http://www.metmuseum.org/art/collection][Metropolitan Museum in New York]]

- [[http://www.mfa.org/collections][Museum of Fine Arts Boston]]
