* Reflection 01: DH Project Profile

Your first assignment is to profile a Digital Humanities project, analyzing its research aims, its form and content, its interface, technologies, and intended audience. You will learn how to navigate Digital Humanities projects, how to identify and evaluate different aspects of such projects, and how to analyze the kinds of knowledge and digital artifacts generated by DH projects. Write-up: 500 words.

You may select any project you like from the syllabus or from one of the pages below:

- [[https://digitalhumanities.duke.edu/all-projects]] (please start here)
- [[https://dhcommons.org/projects]]
- [[https://eadh.org/projects]] 
- [[http://digitalhumanities.unc.edu/resources/projects/]]

This project profile is not an essay; it is a short, 1-2 page report. You do not need to write a formal introduction, thesis, argument, or conclusion. You should only report on your observations, using the questions below as categories of analysis, each with its own heading. Not all categories and questions apply to all projects, so *do not feel obligated to respond to all of them*. Your project profile will be evaluated for [[http://www.artsci.utoronto.ca/newstudents/transition/academic/grading][accuracy, clarity, detail, quality of analysis, and insight]].


1. *Project:* What is the name of the project? Who are its primary authors?

2. *Topic:* What is the project about? (Examples: What topic and historical period does it focus on? What texts or art works or other material does it collect, explain, map, or analyze? What questions is the project seeking to answer?)

3. *People & Institutions*: Who is the project leader? Who are their collaborators? What is the institution involved in the project's development? What are the granting bodies funding the projects? Is credit given to individual contributors? To what extent?

4. *Presentation & User Experience:* What is the “digital artifact” through which this project communicates its findings? A book? A game? A map? An edition? An archive? A tool? Another type of digital artifact?

   As a user external to the project, what steps did you take to explore the project? Can you understand how to read the project's data or how to use the tools it is building? As you explore the project, what do you find easy? What do you find difficult? What do you like? What do you dislike? Document your experience with screenshots, please.

   Does this project provide access to users with e.g. limited bandwidth, minimal computing (e.g. smartphones instead of laptops), vision or hearing or tactile impairment?

5. *Data:*  What data does the project generate? What data format(s): text files, pdf files, digital images, databases, Excel or .csv files? Does the project provide narrative context for its data (that is, does it clearly explain what its data means and why it matters, for readers not familiar with the project)? Is access to project data open, subscription-only, or under a specific licence? May other scholars download the project's data?

6. *Technologies:* What technologies (encoding formats, digital publication platforms, software) are used in this project or built as part of this project? Are these technologies open-source, open-access?

7. *Audience:* Who is the intended audience for this project? That is, does this project primarily speak to laypeople? Scholars? Specialists? How can you tell?

8. *Limitations:* Does the project make note of any limitations in its work, any gaps or uncertainties in its data? Can you find limitations in its work---that is, gaps between its stated goals and its results?

This assignment is based on the [[https://dmptool.org/][DMP Tool]], the U of T DH Census Profile tool, and [[https://docs.google.com/document/d/1jp0bQ18hXKxekgACfBCw_6P6lO_xg4uzUXXMvT2jaPo/edit][Kristen Mapes]]' DH Project Critique assignment.
